### ISSUE TITLE
amoy modified existing file post-discussion

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#10656]
Guys reported next erigon-stuck logs: 
```
INFO[06-06|13:37:31.586] [snapshots] no metadata yet              files=1 list=v1-007600-007700-bodies.seg
INFO[06-06|13:37:31.738] [1/6 Snapshots] downloading header-chain progress="99.90% 1.5GB/1.5GB" time-left=999hrs:99m total-time=5h11m20s download=0B/s upload=0B/s peers=0 files=154 metadata=153/154 connections=0 alloc=98.3MB sys=418.8MB
```

i realized that filename looks familiar and remember that we recently rejected https://github.com/ledgerwatch/erigon-snapshot/pull/178 PR - because some existing file hash changed. But `erigon3-v1-snapshots-amoy.erigon.network` bucket already had new (changed) file. 

So, we need somehow protect from similar future bugs: 
- if erigon/automation by some reason modify/lost existing file 

Random ideas: 
- can have backup/redundancy bucket/folder (which is more immutable). FYI: erigon supports sub-folders like `https://erigon3-v1-snapshots-amoy.erigon.network/backup` (erigon will work with it as with bucket). 
- can have sub-folder for "unreleased yet files", and copy new files from "unreleased" to root after some event. 
- can restore bucket after break
- maybe you have another ideas 

Why erigon modified existing file - i don't know. After i removed this file from snapshotter and re-started erigon - it produced file with old hash (non-modified).

**Comment by michelemodolo** [comment]
OK. Instead of duplicating storage I'd prefer a preventive approach: I'd prefer to change the automation logic so that it proactively checks whether any hash changed. If any change occurs then files are NOT uploaded (and both of us are automatically warned), otherwise files are uploaded. 
Besides I'd like for us to "reserve the right" to have the automation upload the files EVEN IN CASE any hash got changed (there are/might be some rare cases where changed files are good) so I'd also set up a logical switch for that.

**Comment by AskAlexSharov** [comment]
@michelemodolo ok. should we implement logic on erigon side? like add command `downloader hashes_lint`. 
`.kv` files do never-ending merge - so it's ok to see their deletion (when have larger covering files).

**Comment by michelemodolo** [comment]
I'd plan to make a "local_hashes --> official_hashes" comparison so any file which is not present locally (because it was already merged) while still being present in our official .toml wouldn't drive any comparison (so so it's ok to see their deletion). If no hashes change is detected then files are uploaded (and "old files", which got merged, would then be deleted from our official .toml).

**Comment by awskii** [comment]
I think we need to go from both sides:
- add effective check for `downloader` allowing us to be sure of files we releasing: query them, do full scan etc
- add some bash code into PR automation to check if diff provided [contains existing file hash update] or [contains existed file deletion] -> removed by uploading new bigger file or by mistake, alarm. This check could be done in `downloader` as well because we have functions to keep track files which are predecessors for bigger ones. 

alarm, but not prevention of merge or something, in case if we want to update previously released bad file hash, we still should be able to do that without problems

**Comment by AskAlexSharov** [comment]
there is also an "how to rollback files which we released by mistake question", but let's keep it outside of this task. closing as done.
