### ISSUE TITLE
Implement eth_newFilter API method

### ISSUE THREAD

**Issue by 70nyIT** [ledgerwatch/erigon#1736]
# Rationale

**Why should this feature exist?**
Allows turbo-geth to work with command `extract_csv_column` of [ethereum-etl](https://github.com/blockchain-etl/ethereum-etl), required to then proceed to extract all token transfers.

**What are the use-cases?**
If you want to use the archive node as a source of data to enrich a datalake and extract data from (tested using [ethereum-etl](https://github.com/blockchain-etl/ethereum-etl))

**Do you have ideas regarding the implementation of this feature?**
Make it compatible with the standard JSON-RPC [eth_newFilter](https://eth.wiki/json-rpc/API#eth_newfilter)

**Are you willing to implement this feature?**
Don't have enough golang skills

**Comment by KaiRo-at** [comment]
The group of JSON-RPC around filters,  eth_newFilter and  eth_newBlockFilter to create them, and eth_getFilterChanges (sometimes also eth_getFilterLogs) to query them, has been the main way of listening to blockchain events for a long time, so there are many DApps relying on them.
While you can work around them missing via (repeatedly) calling eth_getLogs, those that are not relying on Infura (which also has limitations to filters) are often using filters, esp. as "web3" and similar libraries make it pretty easy to work with those filters usually - even if sometimes they may not be 100% reliable, but that's dependent on the clients/nodes being used.
To make it easy for those DApps to use Erigon, it would be great if you could support this family of calls (and I know, it probably needs its own kind of infrastructure around it, which may be quite some work).

**Comment by 11qu1d** [comment]
I was testing Erigon with my apps as part of migrating away from Geth when to my surprise I stumbled upon this unimplemented family of calls (everything else up this point worked perfectly).

As it was alluded to above, `eth_newBlockFilter` although crude, is a popular way for applications to listen for transactions that are not emitting events either by omission or by design. Not a golang expert but I suspect this feature is not a quick thing to implement. It would be good to see Erigon move towards feature parity with Geth and eventually supersede it.

**Comment by rencryptofish** [comment]
just wanted to check if there were any updates re: this / if it was on the roadmap / is it still an open issue

**Comment by easeev** [comment]
Looking forward for this to be implemented too

**Comment by AskAlexSharov** [comment]
Was implemented by https://github.com/ledgerwatch/erigon/pull/4253
