### ISSUE TITLE
datadir option forces rpcdaemon to run in local db mode

### ISSUE THREAD

**Issue by eduadiez** [ledgerwatch/erigon#2442]
#### System information

Erigon version: `./erigon --version`

```
erigon version 2021.07.4-alpha
```

OS & Version: Windows/Linux/OSX

Linux & Docker
```
git_branch=heads/v2021.07.04 git_tag=v2021.07.04 git_commit=026c4e9d029ae6e91e20111097acb6e6f04b4afd
```

#### Expected behaviour

Using `--private.api.addr=localhost:9090` I expected it to work in remote mode, but I'm getting a `Could not connect to DB`. when I set `--datadir /var/lib/erigon`.

I think that's why you had to add this to the docker-compose:
https://github.com/ledgerwatch/erigon/blob/89ab0615692130e757e4410b1be6b55a88f94726/docker-compose.yml#L44

By removing `--datadir=/home/erigon/.local/share/erigon` from here:
https://github.com/ledgerwatch/erigon/blob/89ab0615692130e757e4410b1be6b55a88f94726/docker-compose.yml#L43

it start to work as expected and there's no need of use `pid: service:erigon`

#### Backtrace

````
rpcdaemon_1  | ERROR[07-24|11:31:54.957] Could not connect to DB                  error="mdbx_env_open: no such file or directory, label: chaindata, trace: [github.com/ledgerwatch/erigon/ethdb/kv.MdbxOpts.Open github.com/ledgerwatch/erigon/cmd/rpcdaemon/cli.RemoteServices main.main.func1 github.com/spf13/cobra.(*Command).execute github.com/spf13/cobra.(*Command).ExecuteC github.com/spf13/cobra.(*Command).Execute github.com/spf13/cobra.(*Command).ExecuteContext main.main runtime.main runtime.goexit]"
````

**Comment by AndreaLanfranchi** [comment]
> Using `--private.api.addr=localhost:9090` I expected it to work in remote mode, but I'm getting a `Could not connect to DB`. when I set `--datadir /var/lib/erigon`.

Your statement is a bit confusing to me.
You say you're expected to work in "remote" mode (aka socket mode) so why would you add --datadir ?
That cli option is only needed if you want rpcdaemon to speed up some queries by a direct access to db.
This said it appears to me you're trying to instantiate rpcdaemon from **a different** docker container than the one erigon is running into. This is highly discouraged due to how locking mechanisms are handled by PID in MDBX

**Comment by AndreaLanfranchi** [comment]
Besides ... your title of issue

> datadir option forces rpcdaemon to run in local db mode

That is exactly what datadir does

**Comment by AskAlexSharov** [comment]
Hi. 
“ Using --private.api.addr=localhost:9090 I expected it to work in remote mode, but I'm getting a Could not connect to DB.” 
1. can’t use  “localhost” inside docker container. 
2. it’s wrong expectation, because local mode also require —private.api.addr, because not everything stored in DB - for example txpool is not in db.

**Comment by eduadiez** [comment]
Yes, you are absolutely right, it has been a misunderstanding on my side.

I'm sorry for wasting your time, you can close it.

**Comment by AskAlexSharov** [comment]
@eduadiez , it ok. Thank you.
