### ISSUE TITLE
Is this really scalable? blk/s decreasing as block height grows

### ISSUE THREAD

**Issue by 1blockologist** [ledgerwatch/erigon#2472]
With the expected behavior of block parsing per second decreasing in speed as the block height grows, it doesn't seem like it will be long before there are many machines that will never catch up.

One of the bragging points of erigon is that "even a hard drive" can keep up.

Maybe if it was synced on an NVMe and copied over to a hard drive.

But even on more higher performant hardware, it seems easy to see that block parsing during initial sync will decline to levels that make it take just as long as other approaches to archival node syncing.

Thoughts?

### Hardware Details

N/A Its not about me

**Comment by AskAlexSharov** [comment]
gasLimit getting bigger, state getting bigger - amount of processing blocks per second getting smaller. No magic. 

Sorry, I don’t want to be involved into abstract discussion - how to solve all problems in the world. 

You can google ETH2, regenesis, parallel transactions execution, refund for selfdestruct, and other topics...

Some recent related links: https://notes.ethereum.org/@vbuterin/verkle_and_state_expiry_proposal

**Comment by 1blockologist** [comment]
That was surprisingly reductive. I was asking if you had a specific plan for this project, imagine if the geth people just said "No magic. Sorry, I don’t want to be involved into abstract discussion - how to solve all problems in the world." when really the last 3-4 years of your life was part of the answer.

The verkle proposal is interesting to think about, thanks. I don't see how ETH2 helps the discussion as the whole point of their sharding system is to accommodate many more states.

**Comment by AndreaLanfranchi** [comment]
Yes there are specific plans to further improve syncing speed.
This said the **full archive node** syncing, considering identical hardware with 16GB Ram and good SSD, is -at current figures- around 1 month with geth and less than 7 days on Erigon. This alone is a huge step ahead and states how Erigon can guarantee (at current figures) a longer lifetime of node's hardware.

**Comment by 1blockologist** [comment]
Ah, wow didn't realize geth had gotten that ridiculous! I have a 4GHz 8 core CPU being used at 20% for most of the 7/18 state syncing phase. I was wondering if that could be utilized more heavily as well as if there was room to offload some aspect to GPU processor its RAM - ultimately to speed things up. Speed up processing time by a few hundred percent, decreasing time by 75%

**Comment by AskAlexSharov** [comment]
You can start from: https://www.youtube.com/results?search_query=turbo+geth

**Comment by AndreaLanfranchi** [comment]
> Ah, wow didn't realize geth had gotten that ridiculous!

To be fair geth **is not** ridiculous. Its code base has proven solid and the fact still holds >80% of network nodes share tells something. Besides, though we renamed to Erigon to state our difference, there probably wouldnt' be any Erigon if it wasn't for geth.

> I have a 4GHz 8 core CPU being used at 20% for most of the 7/18 state syncing phase. I was wondering if that could be utilized more heavily as well as if there was room to offload some aspect to GPU processor its RAM - ultimately to speed things up. Speed up processing time by a few hundred percent, decreasing time by 75%

Taking advantage of full computation capacity of your hardware would be nice to have: unfortunately the rules of the chain make it either impossible or heavily limit this. Multicore processing is possible when **parallel computation is possible** which, in most of stages, actually isn't. Basically every processed block needs data from the previous one(s) hence linear processing is the only way to go. Besides most of operations are IO intensive rather than computation intensive: parallelization of IO intensive ops generally worsen performances.
Usage of GPU resources would then add a lot of boilerplate code only to handle different types of chips (AMD/OpenCL vs NVIDIA/CUDA) with very arguable benefits: GPUs are good at parallel tasks (which we don't have).

**Comment by 1blockologist** [comment]
@AndreaLanfranchi  @AskAlexSharov  Thanks. This is something I was just about to come comment about. Regarding future optimizations and youtube videos I'm not sure what I'm looking for, I watched the ETHLondon interview from last October which seems to be the most recent and basically Alex you are saying that you aren't sure if Erigon will lead to more accessibility of running a node or simply lead to more use cases of Ethereum networks that. But my observation, just like Andrew says, is that Erigon+TurboGeth is only a few percentage points of all reported nodes.

Regardless, what video about future optimizations or possibilities should I be looking for? The ones that are a few years old now I'm assuming are irrelevant, especially after the grant helps you accelerate development.

**Comment by AndreaLanfranchi** [comment]
> But my observation, just like Andrea says, is that Erigon+TurboGeth is only a few percentage points of all reported nodes

We went alpha since less than four months and we're growing fast. Give us time. You can't compare us to geth (yet) but is important to note we're the third node in the rank and also thank to gnosis plans about openethereum we expect to grow even more rapidly. Note we're on the market since less than a year and already surpassed other "new" projects like Nethermind

**Comment by 1blockologist** [comment]
@AndreaLanfranchi nice, you'll zoom to 15% in no time, and that's before the Geth people take notice.

I have a new question for you then, I've been following Turbo Geth since last year primarily for a better archival node. But the new pruned node is interesting as well.

Geth nodes are primarily fast-synced and use 1/3rd of the space of an Erigon archival node, and this may be their primary use case. Any thoughts on what would be attractive to Geth nodes? A pruned Erigon node or a full/archival Erigon node?

**Comment by AndreaLanfranchi** [comment]
Attractiveness depends on usage cases. A full archival node can provide data a pruned node cannot. An erigon full archival node stays to a geth pruned node like apples stay to oranges
On the apples to apples side erigon full archive db footprint is 1/7 of geth's
An erigon pruned node is roughly the same DB size as geth's **but** it verifies the state while geth doesn't
