### ISSUE TITLE
Storage requirement 2.5x larger than geth? 

### ISSUE THREAD

**Issue by egorFiNE** [ledgerwatch/erigon#2569]
Seems like erigon takes about 2.5 times more disk space than geth. 

This is how I run erigon and geth: 

`./erigon/build/bin/erigon --datadir /mnt/erigon/ropsten --chain ropsten --prune=hrtc`

`geth --datadir /mnt/geth/ropsten --ropsten --http --http.api <...>`

And this is the disk space occupied: 

```
291G	/mnt/erigon/ropsten
113G	/mnt/geth/ropsten
```

The same story goes about goerli:

```
78G	/mnt/erigon/goerli/
29G	/mnt/geth/goerli/
```

Am I doing something wrong?

**Comment by AskAlexSharov** [comment]
You need add —gcmode=archive to geth https://geth.ethereum.org/docs/interface/command-line-options
Erigon is archive by default

**Comment by egorFiNE** [comment]
@AskAlexSharov thank you.

Can I switch an existing erigon node to non-archive?

**Comment by AskAlexSharov** [comment]
See —prune flag docs

**Comment by egorFiNE** [comment]
@AskAlexSharov I am running with `--prune=hrtc`.  I have now added `--prune.h.older=10 --prune.r.older=10 --prune.t.older=10 --prune.c.older=10` but erigon says: 

```
err="not allowed change of --prune flag, last time you used: --prune=hrtc"
```

Is it not possible to prune an existing node?

**Comment by AskAlexSharov** [comment]
@egorFiNE , nope. we don't allow to change prune flag on the fly - to easy to delete half of db by human mistake.

**Comment by egorFiNE** [comment]
@AskAlexSharov fair enough. 

I see I can just comment out that verifying condition code. Do you by any change know if commenting out will make old blocks disappear? Judging by a quick test it doesn't seem to free up space.

**Comment by AskAlexSharov** [comment]
pruned node contains all blocks. 
"it doesn't seem to free up space" - yes, this is reason why it prohibited :-) re-sync pls

**Comment by egorFiNE** [comment]
@AskAlexSharov thank you for your explanation! :-) Re-syncing now

**Comment by gituser** [comment]
> @egorFiNE , nope. we don't allow to change prune flag on the fly - to easy to delete half of db by human mistake.

Why not? Re-syncing will take ages instead of deleting old blocks. Is there any other way to do that?



> Seems like erigon takes about 2.5 times more disk space than geth.
> 
> This is how I run erigon and geth:
> 
> `./erigon/build/bin/erigon --datadir /mnt/erigon/ropsten --chain ropsten --prune=hrtc`

It should be pruned already as it says in documentation:

```
--prune value                      Choose which ancient data delete from DB: 
                                      h - prune history (ChangeSets, HistoryIndices - used by historical state access)
                                      r - prune receipts (Receipts, Logs, LogTopicIndex, LogAddressIndex - used by eth_getLogs and similar RPC methods)
                                      t - prune transaction by it's hash index
                                      c - prune call traces (used by trace_* methods)
                                      Does delete data older than 90K block (can set another value by '--prune.*.older' flags). 
                                      Example: --prune=hrtc (default: "disabled")
   --prune.h.older value              Prune data after this amount of blocks (if --prune flag has 'h', then default is 90K) (default: 0)
   --prune.r.older value              Prune data after this amount of blocks (if --prune flag has 'r', then default is 90K) (default: 0)
   --prune.t.older value              Prune data after this amount of blocks (if --prune flag has 't', then default is 90K) (default: 0)
   --prune.c.older value              Prune data after this amount of blocks (if --prune flag has 'c', then default is 90K) (default: 0)
```

Please clarify @AskAlexSharov

**Comment by AskAlexSharov** [comment]
@gituser  “to easy to delete half of db by human mistake”  - is already enough reason. Another reason - you really need to know what you are doing to change it - can’t expect this knowledge from all users. 

“It should be pruned already” - what should be pruned?

**Comment by gituser** [comment]
@AskAlexSharov I understand, but maybe provide a tool and/or a confirmation if someone wants to prune their node and knows what he/she is doing?

Judging from flags @egorFiNE used, the node he was running should be pruned to 90K limit as he provided `--prune=hrtc` and according to documentation it should be pruned, right?

**Comment by AskAlexSharov** [comment]
@gituser we have this tool. It’s in “./build/bin/integration”

“ the node he was running should be pruned to 90K limit as he provided --prune=hrtc”, yes, right. He did try change 90k to other value. Such change will not reduce db size (as he expected).

**Comment by dturner34** [comment]
I know this is old and closed but maybe this is still an issue. More of a usability issue and not necessarily a technical one.  It's weird that erigon syncs an archive node by default and just from what I've seen in chatter, nobody new seems to expect this and are put off when they realize that they have to be down yet another another week to resync, which is then compounded by the fact that they can't tweak a prune setting and correct the issue.   It seems more likely in this situation that users will be forced to drop their entire databases than accidentally dropping half of the databases because they don't understand pruning.
Maybe there just needs to be a simple force flag or confirmation requiring the user to acknowledge they understand the risks.

Erigon has been very stable/usable so far compared to other clients but this default combined with not having this functionality is frustrating.

**Comment by AskAlexSharov** [comment]
“weird that erigon syncs an archive node by default” - it’s weird only until you know that it’s primary use-case and primary focus of team. 

“nobody new seems to expect this and are put off when they realize that they have to be down yet another another week to resync” - 1. we need mention it in the beginning of readme. this is general beginner-unfrendlines of erigon. Been beginner-friendly is big work. 2. Resync is painful - but it only highlighting the problem which need to solve (instead of hiding) - we may ask to re-sync because of bugfix, or hardware failure, etc…


“understand the risks” - but they don’t :-) (do you know what will happen if you enable pruning on archive node?) also we don’t have time to support bug-reports from nodes where prune flag was changed (many more flows to test). We already have force flag: “integration force_set_prune”

**Comment by AskAlexSharov** [comment]
Added some notice about it to readme: https://github.com/ledgerwatch/erigon/commit/e84c43f7dc90e09ed7302352a20acb02fd4a2bb6

**Comment by dturner34** [comment]
Thanks, yeah more of a heads up would definitely help.  Still, users are going to blow right past the documentation and shoot their feet.  It might help to eventually remove the default value for prune so they have to explicitly configure a node for archive, light or full. That way everyone would know what they're getting and there wont be surprises.  Pruning probably also doesn't need as many fine grain options.  it could be determined based on the type of node the user wants and that would probably make the option a little more intuitive and cut down on test paths since you would only have 2-3 different configurations for pruning at that point.  For example, something like `prune.r.before` could be configured with a hard coded value based on the network which could eliminate some human error.  Just some thoughts as I work my way through the api.

**Comment by AskAlexSharov** [comment]
`something like prune.r.before could be configured with a hard coded value based on the network which could eliminate some human error. ` it's already done this way: --prune=hrtc will set hardcoded value based on network name. 

`eventually remove the default value for prune so they have to explicitly configure a node for archive, light or full.` - this is good idea.
