### ISSUE TITLE
Kubernetes: Liveness and Readiness

### ISSUE THREAD

**Issue by ArchiFleKs** [ledgerwatch/erigon#2703]
Hi, I'm using Kubernetes and would like to know if there is specific endpoint to see if the node is syncing or is synced ?

**Comment by JekaMas** [comment]
For liveness I believe you could use any request. For sync status we have https://eth.wiki/json-rpc/API#eth_syncing, which should work as in go-ethereum. It might be used for readiness if you'd like to use Erigon only after full sync, otherwise it's better to describe what API you need and look for proper way to check that this API is ready to go.

**Comment by AskAlexSharov** [comment]
I advise use eth_syncing, because other methods we may cache in future. 

But actually I think we need (in all services): https://github.com/grpc/grpc/blob/master/doc/health-checking.md

**Comment by Kampe** [comment]
@ArchiFleKs you by chance care to publish your manifests?  would love to create a chart for this!

**Comment by ArchiFleKs** [comment]
@Kampe sure they are available here https://github.com/fragmentsh/helm-charts/tree/main/charts/erigon

**Comment by ArchiFleKs** [comment]
FYI, I had some issue with Geth sync API because pod was getting not ready every time a block was received which caused network interruption. I have not restested wth Erigon since
