### ISSUE TITLE
Chaindata on HDD not feasible, looking for solutions to reduce MDBX size or to make it faster on slow drives

### ISSUE THREAD

**Issue by Tronic** [ledgerwatch/erigon#2772]
Would it be possible to split cooler and hotter parts of the database to separate files? If COW is used on btrfs, erigon instantly fragments the database like crazy, making it very unusable. Because compression can only be used with COW, the database then takes 1.5 TB of disk space (and growing quickly by each day).

If old blocks and any indices that don't need to be constantly refreshed could be stored in a separate file, one could enable COW and compression for that, while keeping the current changes on a flat unfragmented file. Further, one could envision keeping bulk data on HDDs and dedicating SSD space on a separate filesystem only for the frequently modified parts.

**Comment by Tronic** [comment]
Okay, at least the nodatacow Erigon seems to be running decently well on the SSD-cached HDD RAID now, and spending 1.5 TB of HDD is not that expensive but the HDDs are quite heavily loaded still.

**Comment by gituser** [comment]
Many thanks to @Tronic for this research.

I was considering switching from [openethereum ](https://github.com/openethereum/openethereum) (ex parity) to erigon to run it on HDDs (as NVME/SSD storage is quite expensive) but it seems it's not ready for it at all.

Furthermore, you can't even split data across multiple storage devices as there is only 1 big file mdbx.

On openethereum you could at least move old files to HDD storage and leave e.g. fresh 30 days history on SSD and this way reduce it's usage on SSD.

@AskAlexSharov somewhere I saw that erigon is capable running on HDDs it seems this claim gone now, I think at this stage it should be noted erigon can only be run on SSDs.

**Comment by AskAlexSharov** [comment]
You may trust this tweet https://twitter.com/paolorebuffo/status/1400574790679867396?s=21

It’s possible to run Erigon on most modern latency-oriented HDD - if you are not in rush and keep real-time tip of chain is not important. But we never recommended it. Some guys had this as a dream - but never get there. 

We don’t have warp sync yet - can’t move only ancient blocks to hdd now.

**Comment by AskAlexSharov** [comment]
--syncmode=snap released
now you can mount datadir/snapshots to HDD and datadir/chaindata to faster disk
snapshots are using ReadAhead feature of OS (because they store data sequentially) - at least during genesis sysnc

future release of Erigon2 will move more data to Snapshots (only blocks now).

in some places parallelisation and warmup are added (but not everywhere). 

I have thinking about some new flag (aka --disktype=throughput) which will switch erigon to HDD-friendly or CloudHighThroughputDisk-friendly modes. But it's only in dreams now.

**Comment by mtgnoah** [comment]
> now you can mount datadir/snapshots to HDD and datadir/chaindata to faster disk

So what will the storage savings be for this? 225gb for the snapshots or are the storage savings greater than this?

**Comment by AskAlexSharov** [comment]
https://erigon.substack.com/p/disk-footprint-changes-in-new-erigon?s=r

**Comment by guglez** [comment]
@AskAlexSharov did those dreams about CloudHighThroughputDisk friendly modes come true?

**Comment by AskAlexSharov** [comment]
> @AskAlexSharov did those dreams about CloudHighThroughputDisk friendly modes come true?
 
Progress is here, but you will suffer anyway. (for example I have mainnet on gcloud pd-ssd). 

- I did add several “parallel warmup” places to Erigon2
- main problem of such disks: or you need parallelize work (read+transform). Or you need mass parallel read - and single-thread transform based on data in RAM. And it’s unclear “how much parallel warmupers it must use”. 
- another option is: Moving data out of DB allow change MADVISE, and it’s kind of better than parallel warmup. Erigon3 does it and it getting closer. 
- another option: use zfs with big pageSize (and increase page-size in erigon too). It will read more data at once and waste more ram (and likely reduce fragmentation), but overall reduce amount of disk reads. Increase ram will also help - but will need handle server reboot somehow (by some parallel warmup like “integration warmup —table=PlainState”, latest versions of mdbx_dump also have new flags -u/-U) - of course it can be automated if erigon can detect disk type. 
- erigon using madv_random on DB - to reduce ram waste. But maybe changing it may help for cloud drives (no time to test it much). 
- Also not always clear - how erigon can detect disk type.

**Comment by J-A-M-E-5** [comment]
@AskAlexSharov very interesting discussion.

I have LVM RAID0 across 2 SSD's, with a ext4 partition dedicated solely to Erigon chaindata (snapshots are on HDD). I can snapshot this partition with LVM snapshot and then restart the node and have reliable reasonably quick backup. Now I could use btrfs maybe and use btrfs snapshots.

I remember when I striped my LVM RAID I selected 32kb stripe size. So this means 64kb across 2 SSD array. Now I'm not sure if this means I should recompile kernel, format the LVM partition as 64kb ext4 (normal kernel supports 4k).  Or use 32kb ext4. Change erigon mdbx page size to match. Or can I used the erigon db as a block device and skip filesystem altogether and have the file be the partition? This would remove fs-layer from the equation so I'd only have to worry about stripe size of RAID0 array, and page size of erigon db, and of course any attempts by the database to grow!

There's so many variables I'd love to test all, but you can imagine the time syncing or dumping/loading to get a real-world config.

**Comment by AskAlexSharov** [comment]
@J-A-M-E-5 
1. change mdbx page size is ok. bigger pages -> less fragmentations and metadata -> smaller db. but also increasing overall write amount - but it may help for HDD because of less fragmentation. 
2.  used the erigon db as a block device - no. But you may try reduce FS impact by increasing `mdbx GrowthStep` (less grow steps -> less file fragmentation -> smaller FS/OS metadata to convert virtual addresses to physical. LMDB - by this reason doesn't allow grow/shrink to minimize this factor as much as possible - need re-open db to increase db size (but usually just create huge db from beginning). But in Erigon and MDBX we did 1 step towards usability vs performance).  
3. we had "erigon on zfs" thread in discord with much of related info and benchmards - but seems somebody deleted it. 
4. FYI: Erigon3 is getting closer - it moving state history and historical indices to snapshots. Mainnet now looks as: `700GB /erigon/snapshots/history/`, `300GB chaindata`.

**Comment by AskAlexSharov** [comment]
5. We didn't update mdbx for long time (probably will do in Erigon3). It has new feature in WRITE_MAP mode: by using `minicore()` it can avoid generating page-fault for pages which we plan fully re-write (so called pre-fault). It can be game changer for initial sync on HDD.

**Comment by AskAlexSharov** [comment]
Found zfs thread: https://discord.com/channels/687972960811745322/1049704837564084245
