### ISSUE TITLE
--maxpeers argument not honored

### ISSUE THREAD

**Issue by AndreaLanfranchi** [ledgerwatch/erigon#2853]
#### System information

git_branch=devel git_tag=v2021.09.03-125-g96ea5438d git_commit=96ea5438d9a4fb72637937ca5e79a545b9a2cc20

OS & Version: Windows And Linux

Commit hash : 96ea5438d9a4fb72637937ca5e79a545b9a2cc20

#### Expected behaviour

The total number of connected clients (regardless the protocol) should not exceed the value of `--maxpeers` cli argument (which defaults to 100)

#### Actual behaviour

The limitation is actually applied per protocol.
```
INFO[10-20|18:44:12.319] [p2p] GoodPeers                          eth66=100 eth65=79
```

**Comment by DanielAtCosmicDNA** [comment]
## The problem
The question that arises from this is:
- How to balance each protocol in order to guarantee the overall sum will be no more than `MaxPeers`?

In terms of control it becomes more complex to manage which protocol is to be favoured in order to max out the number of peers. That means deciding which peers to drop and which peers to add in such a way to respect `MaxPeers` single boundary.

## Improvement Proposal
`MaxPeers` can rather be an array of values symbolizing each protocol limit rather than one single value.
In this improvement proposal, the user is supposed to pass an array of comma separated values as follows:
- erigon --maxpeers 100,100

Erigon can then safely use default 100 and 100 values if no `MaxPeers` is provided

**Comment by AskAlexSharov** [comment]
Using arrays is very unsafe. Imagine that I will add new eth67 protocol support or drop eth65 or both. In this cases flags of user will get invalid. We already have ` --p2p.eth65.port` parameter. I think we can add more params to ` --p2p.eth65.*` namespace. One of them also to disable eth65 :-)

**Comment by mandrigin** [comment]
so, didn't we drop eth65?

**Comment by AskAlexSharov** [comment]
@mandrigin we did.
