### ISSUE TITLE
add application identifier to monitoring metrics option

### ISSUE THREAD

**Issue by gMonty030** [ledgerwatch/erigon#3200]
# System information
Erigon version: erigon version v2021.12.03-beta

# OS & Version: 
linux/amd64 Linux 5.11.0-1019-aws #20~20.04.1-Ubuntu SMP x86_64 Linux

# Rationale
We use a Prometheus instance connected with other applications, which have their own identifier on their metrics functions. This allows to differ them between other functions more generically. 

Could be possible to add a prefix to the metrics¿? (i.e: erigon_get_logs)

**Comment by AskAlexSharov** [comment]
This looks as "hack" - because prometheus adding `instance` label to all metrics. 
Filter by label is more "generic" that filter by prefix (with regular expressions?). Example: How you will show metrics of 2 Erigon instances if both will have hardcoded prefix "erigon_"? 

In dashboard configuration - can dynamically extract this labels list (from any metric): 
<img width="969" alt="Screen Shot 2022-01-05 at 10 51 30" src="https://user-images.githubusercontent.com/46885206/148158035-8f9c65ca-d2bf-4482-802e-ed317f3dd855.png"

It will create multi-select filter on board: 
<img width="1336" alt="Screen Shot 2022-01-05 at 10 52 56" src="https://user-images.githubusercontent.com/46885206/148158200-d71e1323-6fdc-4a59-a6b6-986d319e01c9.png">

And metrics usage will look as `get_logs{quantile="$quantile",instance=~"$instance"}`:
<img width="908" alt="Screen Shot 2022-01-05 at 10 56 39" src="https://user-images.githubusercontent.com/46885206/148158401-8ad78ea9-b08e-45ea-8fdf-c4307b3d0386.png">

**Comment by AskAlexSharov** [comment]
@gMonty030 still it's a bit not good way to fix Prometheus UX problem. Because for us better have some compatibility with `geth` - if we add prefix - we break all compatibility. There is one more way to handle this - label `job` - which you set when configuring Prometheus's scrape targets:
```
// ./cmd/prometheus/prometheus.yml
scrape_configs:
    - job_name: erigon 
```
then in prometheus you can see all metrics from all instances of erigon 
<img width="1344" alt="Screen Shot 2022-01-11 at 12 07 24" src="https://user-images.githubusercontent.com/46885206/148884672-a1de6bb1-84e8-46ad-b89d-c8f125da7f63.png">

**Comment by gMonty030** [comment]
This approach could be more than enough. Makes sense after knowing the compatibility concerns. 
Thanks, I close the issue
