### ISSUE TITLE
Execution failed -bsc

### ISSUE THREAD

**Issue by masayil** [ledgerwatch/erigon#3566]
[EROR] [02-21|17:09:38.536] [6/16 Execution] Execution failed        block=7192418 hash=0x6be58555b813340c2f5e449fff71f4be2654434f3d395eb7a7
0eeba96fb21916 error="expected system tx (hash 0x1f1adba6cf72635eb9c8c82575236fd84a570781618e7c5b8b94879372b83c23, nonce 60874, to 0x0000000
000000000000000000000000000001002, value 0x28973dfb63acac, gas 9223372036854775807, gasPrice 0x0, data ), actual tx (hash 0x603a5ed9ca59eb10
bd1d24a76cfb6d897bca7ee7ffe4b473e95db3b079534b2e, nonce 60874, to 0x0000000000000000000000000000000000001002, value 0x288f97313cf74c, gas 92
23372036854775807, gasPrice 0x0, data )"
[INFO] [02-21|17:09:38.540] UnwindTo                                 block=7192417 bad_block_hash=0x6be58555b813340c2f5e449fff71f4be2654434f
3d395eb7a70eeba96fb21916
[INFO] [02-21|17:10:08.540] Write to db                              progress=0.3M/3.9M current table=PlainCodeHash
[INFO] [02-21|17:10:11.158] [p2p] GoodPeers                          eth66=30
[INFO] [02-21|17:10:38.541] Write to db                              progress=2.9M/3.9M current table=PlainState
[INFO] [02-21|17:12:11.159] [p2p] GoodPeers                          eth66=30
[INFO] [02-21|17:13:13.198] [6/16 Execution] Completed on            block=7192417
[INFO] [02-21|17:13:13.199] [6/16 Execution] DONE                    in=70h49m18.427470158s
[INFO] [02-21|17:13:43.398] [4/16 Bodies] Unwinding transactions...  current block=7193354
[INFO] [02-21|17:14:11.159] [p2p] GoodPeers                          eth66=30
[INFO] [02-21|17:14:13.373] [4/16 Bodies] Unwinding transactions...  current block=7194508
[INFO] [02-21|17:14:43.364] [4/16 Bodies] Unwinding transactions...  current block=7195550
[INFO] [02-21|17:15:13.390] [4/16 Bodies] Unwinding transactions...  current block=7196379
[INFO] [02-21|17:15:43.364] [4/16 Bodies] Unwinding transactions...  current block=7197095

**Comment by AskAlexSharov** [comment]
Try latest devel

**Comment by temuera** [comment]
> Try latest devel

The BSC network never worked successfully.
I had to create a official geth archive instance  on the last time I resync erigon. 

I would suggest changing to a step sync mode and compacting every 1 million blocks when not catching up to the latest blockNumber.

Current Mode is : block start -> highest block number -> stage loop(last block->highest block)
Change to: stage loop(last block -> last block + 1000k) ->stage loop(last block->highest block)

In this way, you can use the synchronized data for project development while waiting for erigon node synchronization.

Otherwise the cost is simply too high for find error. Every time a problem is found takes a week, and it may be necessary to start over.

the last commit: b49381821f6420bf115998a6b8307bd646995818 [b493818]  **still fails block 7192418.**

**Comment by perfectcircle2020** [comment]
@zzh1996  Hey man, would you `rsync` your mdbx database in my backup box ?

I want to create a snapshot and share it via torrent.

**Comment by AlexeyAkhunov** [comment]
> the last commit: [b493818](https://github.com/ledgerwatch/erigon/commit/b49381821f6420bf115998a6b8307bd646995818) [[b493818](https://github.com/ledgerwatch/erigon/commit/b49381821f6420bf115998a6b8307bd646995818)] **still fails block 7192418.**

Unfortunately, the bug creates wrong state in the db, and to fix you need to repeat the sync, or at least the execution stage

**Comment by temuera** [comment]
> > the last commit: [b493818](https://github.com/ledgerwatch/erigon/commit/b49381821f6420bf115998a6b8307bd646995818) [[b493818](https://github.com/ledgerwatch/erigon/commit/b49381821f6420bf115998a6b8307bd646995818)] **still fails block 7192418.**
> 
> Unfortunately, the bug creates wrong state in the db, and to fix you need to repeat the sync, or at least the execution stage

shivered when heard the word resync... lol~
