### ISSUE TITLE
Pruining while in execution stage

### ISSUE THREAD

**Issue by perfectcircle2020** [ledgerwatch/erigon#3658]
Hello,

I have a question, I started syncing again my node and this time I wanted to change the prune parameters while I reached 10m block execution.

So I changed the following flags:

` --prune.h.before 70000 --prune.r.before 70000 --prune.t.before 70000 --prune.c.before 70000`

to these:

` --prune.h.before 10000000--prune.r.before 10000000--prune.t.before 10000000--prune.c.before 10000000`

But no effect was seen so far, do I need to do something else for the new parameters to be considered?

_The node is eating space like cake is eaten at my birthday._

**Comment by AskAlexSharov** [comment]
@perfectcircle2020 
1. `10000000--prune.c.before` you lost space
2. We do prohibit changing prune settings - because it's very easy to do "human mistakes" here, and likely it will not do what you expect. 
3. Please read `--prune.*.older` and `--prune.*.before` flags difference in `erigon --help`
4. Describe your use-case - why default --prune settings do not work for you? Is this what you looking for: https://github.com/ledgerwatch/erigon#beacon-chain ?
5. "The node is eating space like cake is eaten at my birthday." - please avoid non-measurable sentences. It's impossible to extract any valuable information from such sentences, but they may touch people's emotions. 
Thank you.

**Comment by perfectcircle2020** [comment]
@AskAlexSharov 

Thank you for the reply.

1. I am aware of that, It was a mistake while copying and pasting.
2. I understand, I would like to prune block bodies, to free some space :)
3. I want to save up space in the same manner `--prune=hrtc` saved in previuos sync attempts, while now save even more space by keeping only the last blocks, Is it possible given the circumstances?


Thank you

**Comment by AskAlexSharov** [comment]
@perfectcircle2020 yes, Please read --prune.*.older and --prune.*.before flags description in erigon --help. likely you wanna use another `older` flag.

**Comment by perfectcircle2020** [comment]
@AskAlexSharov  Thanks

I came up with the following parameters:

`--prune.h.older=50000  --prune.r.older=50000 --prune.t.older=50000 --prune.c.older=50000 --prune.h.before=0 --prune.r.before=0 --prune.t.before=0 --prune.c.before=0`

Is it correct this way the node will keep only the last 50K blocks? 

Thanks

**Comment by AskAlexSharov** [comment]
1. if you set `--prune.h.older` then no reason to set `--prune.h.before`
2. default `--prune` parameter is shortcut for `--prune.h.older=90_000 --prune.r.older=90_000 --prune.t.older=90_000 --prune.c.older=90_000`. so, probably just add one flag `--prune` is good enough for you.

**Comment by perfectcircle2020** [comment]
@AskAlexSharov Thank you for the clarification. 

I am now using  only the older flag, but still the occupied space is increasing very fast, I am worried I will run out of space before the node will be fully synced. 

Is it expected behavoir?, or do I need to perform some other actions in order for the prune operation to take place?

Thank you

**Comment by AskAlexSharov** [comment]
Can't advise if you don't show for me details:
- "now using only the older prune flags" - don't describe it by words, just past cli flags here. 
- "increasing very fast" - don't describe it by words, just show `du -h` and current erigon logs, and say what size do you expect.

**Comment by perfectcircle2020** [comment]
Ncdu:
![immagine](https://user-images.githubusercontent.com/88373598/157807247-84c172cc-5a17-42bc-8a3c-94b9d7217954.png)

While I was syncing from scrath with `--prune=hrtc` the size of the database wouldn't be higher than 1.4 TB.

Now that I am using these: 

`./erigonv1 --chain bsc --datadir bsc-mainnet --prune.h.older=90000  --prune.r.older=90000 --prune.t.older=90000 --prune.c.older=90000`

The space occupied is like in the image.

Thank you

**Comment by AskAlexSharov** [comment]
show logs of erigon when it starts - it does print which flags it using

**Comment by perfectcircle2020** [comment]
![immagine](https://user-images.githubusercontent.com/88373598/157808363-4a33dd25-f194-481e-8ef7-30b522ef0f87.png)

**Comment by AskAlexSharov** [comment]
see "Effective" line. It shows `--prune=` it means pruning is disabled. likely you need add flag `--prune` to enable it - even if you configure all other --prune.* flags

**Comment by perfectcircle2020** [comment]
Thank you!!!

**Comment by AskAlexSharov** [comment]
I also didn't know about it

**Comment by perfectcircle2020** [comment]
![immagine](https://user-images.githubusercontent.com/88373598/157808695-cd8837da-cfd4-4e7e-a316-971574cb3234.png)

**Comment by AskAlexSharov** [comment]
I just tested `--prune=hrtc --prune.r.older=123` works

**Comment by perfectcircle2020** [comment]
Thank you!!

**Comment by perfectcircle2020** [comment]
I pulled newest version from github and compiled and started again it says that:

![immagine](https://user-images.githubusercontent.com/88373598/157809427-6e97be55-4010-497c-878b-4770162385dc.png)

**Comment by AskAlexSharov** [comment]
some database format change migration

**Comment by perfectcircle2020** [comment]
@AskAlexSharov Unfortunatelly after the migration I still get:

`EROR[03-12|15:51:11.219] Erigon startup                           err="not allowed change of --prune flag, last time you used: --prune="  `

And have even more space occupied

![immagine](https://user-images.githubusercontent.com/88373598/158022826-a1c4f8a3-3062-4127-8024-5d419e1a69b2.png)

**Comment by AskAlexSharov** [comment]
Already told you: 
`We do prohibit changing prune settings - because it's very easy to do "human mistakes" here, and likely it will not do what you expect.`
We have tool to force change prune flag, but we don't recommend to use it - because it will not do what you expect and can lead to problems  
I advise you re-sync with right set of flags.

**Comment by newearthmartin** [comment]
Hello @AskAlexSharov , I started syncing my node and when it got to block execution stage I ran out of space. Now I wanted to add prune flags but I get this message `not allowed change of --prune flag, last time you used`.

2 questions:

- is there a way I can resync with the correct prune flags without having to download the snapshots again?
- what are the correct prune flags for staking?

1 request:

Can you please add a section about this in the documentation? especially since one can not change the prune flags later.  It would be specially useful near (or linked in) this part:

> Ethereum Mainnet Full node (see --prune* flags): 400Gb (April 2022).

**Comment by newearthmartin** [comment]
I removed the `chaindata` folder but kept the `snapshots` folder and now it started.

**Comment by AdminAnticaptcha** [comment]
@newearthmartin thanks for the comment, seems that syncing now went straight to the end of the blockchain.

They don't want to put it in project README, because there will be no people left with full archive to sync from. They want to put the expense of storing all those terabytes of data on user's shoulders.

**Comment by newearthmartin** [comment]
> They don't want to put it in project README, because there will be no people left with full archive to sync from. They want to put the expense of storing all those terabytes of data on user's shoulders.


@AdminAnticaptcha This is irrelevant as erigon syncing is done through snapshots.
