### ISSUE TITLE
Erigon docker permission issue

### ISSUE THREAD

**Issue by breezytm** [ledgerwatch/erigon#3950]
Can a step be added in the dockerfile to set the right permissions for the erigon user

```
[EROR] [04-24|03:34:02.589] Erigon startup                           err="migrator.VerifyVersion: cannot upgrade major DB version for more than 1 version from 3 to 6, use integration tool if you know what you are doing"
[INFO] [04-24|04:09:14.575] Build info                               git_branch=alpha git_tag=v2022.04.03 git_commit=9ccc76afccdeed009961bfa95332cf0f7026bbd7
[INFO] [04-24|04:09:14.575] Starting Erigon on Ethereum mainnet... 
Fatal: failed to save node key to /home/erigon/.local/share/erigon/nodekey: open /home/erigon/.local/share/erigon/nodekey: permission denied
Fatal: failed to save node key to /home/erigon/.local/share/erigon/nodekey: open /home/erigon/.local/share/erigon/nodekey: permission denied

```

**Comment by AskAlexSharov** [comment]
datadir is mounted volume - it doesn't exists when Docker build happening

**Comment by victordeleau** [comment]
The error you have is because the container is not running erigon as root internally, but as a regular user `erigon` with UID/GID 1000, which is preferred for security reasons. You can see this user being created in the [Dockerfile](https://github.com/ledgerwatch/erigon/blob/devel/Dockerfile).

When it comes to mounted volumes, docker maps the container's users to the host's users using their UID/GID. If there is no UID/GID match, or if the mapped host user has no right over the host's folder that you're mounting, you will get a permission denied error. 

I fixed it by giving a host's user ownership of the folder, where the host's user UID/GID is the same as the docker's user UID/GID (1000).

More details in this [post](https://www.fullstaq.com/knowledge-hub/blogs/docker-and-the-host-filesystem-owner-matching-problem).

**Comment by breezytm** [comment]
Thank you @victordeleau for the details on this. To temporary bypass the issue, I gave full permission to everyone on the folder. I was going to suggest why not run as root instead of the erigon user but now I understand better so again thanks for sharing. This case can be closed as others facing this issue would be able to find and use it as a reference.

**Comment by AskAlexSharov** [comment]
@victordeleau added your reply to FAQ section of main readme
