### ISSUE TITLE
“make docker-compose” on Linux has “file permissions” error

### ISSUE THREAD

**Issue by AskAlexSharov** [ledgerwatch/erigon#4267]

**Comment by victordeleau** [comment]
I tried `make docker-compose` and got `ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?`.
I do have `docker` installed. If I run `sudo make docker-compose`, `docker` is found and the command does what it's supposed to do.

I think the reason is because a default install of `docker` will be such that `docker` will require sudo and run as root. Although it's not recommanded to run `docker` as root (and therefore the containers) for security reasons, it's up to the user to allow a non-root user to run `docker`. 

Here is how to run `docker` as a non-root user -> https://www.thegeekdiary.com/run-docker-as-a-non-root-user/

I don't know if something needs to be done in the repo though.

**Comment by AskAlexSharov** [comment]
at least need write something in readme or docker-compose.yml comments
also erigon's dockerfile using special UID, likely volumes must be owned by this UID.
maybe something else.

**Comment by victordeleau** [comment]
A small MR -> #4296 https://github.com/ledgerwatch/erigon/pull/4296

For the UID, I can see you already added some documentation about it in the readme.

**Comment by mandrigin** [comment]
@AskAlexSharov is that the fix that you mentioned today?

**Comment by AskAlexSharov** [comment]
yes
