### ISSUE TITLE
--rpc.accessList problem

### ISSUE THREAD

**Issue by masayil** [ledgerwatch/erigon#4541]
When I add the flag `--rpc.accessList=/root/svc/rules.json` , `--http.api "eth,web3,net"`  it doesn't work

**Comment by masayil** [comment]
![image](https://user-images.githubusercontent.com/65291464/175794958-af5ec346-ca55-415e-8ae3-eaec17ee2033.png)
If I want to enable RPC methods - `eth_newBlockFilter, eth_newPendingTransactionFilter, eth_newFilter, eth_getFilterChanges` , I have to manually add the other rpc methods under namespaces `eth,web3,net` into the `rules.json`

**Comment by AskAlexSharov** [comment]
Please be carefull with asterisk(star) “*” - shell may replace it with files list.

**Comment by masayil** [comment]
> Please be carefull with asterisk(star) “*” - shell may replace it with files list.

![image](https://user-images.githubusercontent.com/65291464/175803639-622c30af-e22d-45f4-8e93-03d36ca03292.png)
I remove it!

`--rpc.accessList`   overrides the parameter `--http.api`

**Comment by wmitsuda** [comment]
when you use --rpc.accessList, you need to specify *ALL* individual methods in the rules.json file. I know that because I use the same configuration, both params work together ("AND").

So, --http.api means "you are allowed to use those namespaces", but specifying --rpc.accessList reset all allowances.  But specifying only --rpc.accessList is not enough, but need to specify the methods AND enable the namespaces in --http.api.
