### ISSUE TITLE
Incorrect eth_gasPrice for rinkeby

### ISSUE THREAD

**Issue by mikolajsobolewski** [ledgerwatch/erigon#4634]
#### System information

Erigon version: `./erigon --version`
````
erigon version 2022.07.1-alpha-09776394
````
Erigon running options:
````
./erigon --chain=rinkeby  --port=30303  --private.api.addr=127.0.0.1:9090  --http --http.addr=0.0.0.0 --http.vhosts=* --http.port=8545 --http.api=eth,debug,net,trace,web3,erigon --ws --torrent.download.rate=20mb --torrent.port=42069 --prune=htrc
````

Erigon on the rinkeby returns incorrect  gas price value
Actual gasPrice
````
curl -X POST --header "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_gasPrice","params":[],"id":1}' http://localhost:8545
{"jsonrpc":"2.0","id":1,"result":"0x11a"}
````
Behavior gasPice (get from geth)
````
curl -X POST --header "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_gasPrice","params":[],"id":1}' http://172.17.0.3:8545
{"jsonrpc":"2.0","id":1,"result":"0x59682efe"}
````

**Comment by mandrigin** [comment]
@mikolajsobolewski can you check if it reproduces on the latest `devel` build?

**Comment by mandrigin** [comment]
We need to cover this RPC with unit-tests so it doesn't regress further.

**Comment by mikolajsobolewski** [comment]
> @mikolajsobolewski can you check if it reproduces on the latest `devel` build?

i confirm, it seems ok.

**Comment by mandrigin** [comment]
okay, I will keep it open until we add unit tests

**Comment by hexoscott** [comment]
I've added some unit tests, but before putting in a PR it looks like there are some other issues at play.

The original regression around -1 being passed for the block number to get the latest causing a buffer underflow is resolved by the code changes in #4528 and #4635 but because we create a fresh oracle for every RPC request the default price will always be returned (0 based on the default config in `ethconfig.Defaults.GPO`).  It looks like this is the problem found in #4630.  

The oracle code is doing a few locks/checks around reading the cached value which won't exist as we have a fresh instance every time so could we take this chance to fix up the Oracle to skip the cache checks and let the ethAPI code handle holding on to the last known good gas price in a cache of its own?

**Comment by hexoscott** [comment]
Raised the PR anyway, can adjust as needed:

#4705

**Comment by mandrigin** [comment]
covered by unit-tests too, closing this one
