### ISSUE TITLE
Issue at Sepolia Merge

### ISSUE THREAD

**Issue by nalepae** [ledgerwatch/erigon#4660]
#### System information

Erigon version: `v2022.07.01` (Docker image on Kuberneted)

During Sepolia merge, I used multiple combos:

1. Geth - Teku
2. Geth - Prysm
3. **Erigon - Teku**

Everything went well for combos 1. and 2., however for combo 3. (Erigon - Teku) our validators missed some attestations right after the merge.

Example of missed attestation:
<img width="468" alt="image" src="https://user-images.githubusercontent.com/4943830/177580164-e28dd0fc-a910-45c2-92b7-35c3ecbc5ed6.png">

https://sepolia.beaconcha.in/validator/8bb045e7482b7abe670d72eb2f7afe4207b5a3d488364ff7bb4266f8784ea41893553a4bf7d01e78c99ed9008e2c13bb

I'm not 100% sure it is Erigon related (might be Teku), but since my combo 1. did not had any issue, I assume it is Erigon related.

Please find the logs bellow for:
- Erigon
- Teku Beacon
- Teku Validator

**Erigon:**
https://pastebin.com/04Fp9meu

**Teku Beacon:**
https://pastebin.com/rX6JAjZM

**Teku Validator**
https://pastebin.com/ha4bWbH7

**Comment by Giulio2002** [comment]
Attestation are not handled by EL

**Comment by Giulio2002** [comment]
that is probably because we were reverting the invalid side fork, it should not persist after, but failing to attest once or twice is not a big deal usually

**Comment by Giulio2002** [comment]
it seems proposals are going through so i would not worry about a couple of attestations failed on a chain revert.

**Comment by nalepae** [comment]
This issue only happened right after the merge.
It is OK right now (without rebooting any clients/validator)

**Comment by mandrigin** [comment]
okay, then I will close it for now, feel free to reopen if you see some major issues

**Comment by nalepae** [comment]
> but failing to attest once or twice is not a big deal usually

I understand, but in our case all my validators connected to Erigon failed to attest once or twice, furthermore just after the merge.

> additionally the client syncing should not impact attestations in sepolia's case unless someone committed a new validator exactly at that time

After a quick talk with Ben Eddington (Teku), we conclude to that:

1. EL (Erigon) is out of sync right after the merge, which implies that
2. All calls from BN (Teku) to EL (Erigon) returns 503 (service not available), which imples that
3. No attestations are done since we may attest to an invalid block

The root cause of missing attestations seems to be "Erigon is out of sync".

==> Do we have an explanation why Erigon was out of sync right after the merge?
(I just try to understand what happened)

**Comment by Giulio2002** [comment]
If your validators are all connected to the same node, they will without a doubt present the same problem if there is a network mishandling. I do not think that it is worth having a ticket for a couple of missed attestations since the issue wont be too significant anyway.

**Comment by mandrigin** [comment]
Erigon does become out of sync every now and then and Teku doesn't really like it. We run couple of thousands validators on Erigon + Teku combination and sometimes it misses attestations. It looks like both nodes are waiting for each other at that point, but I never dig too deep into it. I think post-ethCC I can spend more time figuring out the issue. We didn't have that with Prysm.

**Comment by aimxhaisse** [comment]
+1 @mandrigin 

(we ran prysm/geth & teku/erigon for the merge and this issue only manifested on teku/erigon; we also operate teku at scale on goerli with geth without hiccups)

This issue happened right at the moment of the Sepolia merge when it was supposed to flip to the consensus layer. If this issue is merge-related, and everyone was using Erigon at the time, the merge would not have happened there.

Is there a way to rule out this is not a merge related issue? If not, should Erigon be deprecated for the window of the merge itself?

**Comment by mandrigin** [comment]
@aimxhaisse that is why I run teku with Erigon, to make sure we have everything ready by the time of “the merge” itself… So I think you don’t need to change the EL just for the merge period, there is still time to fix issues and in the end.

Also, Goerli didn’t switch to the beacon chain yet, so that doesn’t matter, we run many Erigon-based validators on mainnet and those are rock solid. But pre-merge Erigon just need to provide responses for eth_getLogs basically :)
