### ISSUE TITLE
Incorrect transaction debug output on BSC

### ISSUE THREAD

**Issue by quickchase** [ledgerwatch/erigon#5865]
Using the latest version on BSC: `v2.28.1` (and older versions)

The following trace is incorrect:
```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "debug_traceTransaction",
  "params": [
    "0xebf83628ba893d35b496121fb8201666b8e09f3cbadf0e269162baa72efe3b8b",
    { "tracer": "callTracer" }
  ]
}
```

It returns:
```
"error":"execution reverted"
```

However, this transaction is successful (the receipt says it was successful too):
https://www.bscscan.com/tx/0xebf83628ba893d35b496121fb8201666b8e09f3cbadf0e269162baa72efe3b8b

Same output if you do `debug_traceBlockByNumber`

May be related to #5308

**Comment by MysticRyuujin** [comment]
As was pointed out on Discord. The address in question that submit this transaction was part of the `NanoBlackList` - which means that the likely cause of this issue is that the state transition logic is returning an error instead of allowing the transaction to complete because of the "dumb" nature of the blacklist.

**Comment by MysticRyuujin** [comment]
It's still a problem
