### ISSUE TITLE
a bug of api 'trace_get' 

### ISSUE THREAD

**Issue by shu-unifra** [ledgerwatch/erigon#5881]
#### System information

Erigon version: `./erigon --version`

OS & Version: Windows/Linux/OSX

Commit hash : b437fab006b8df7d8622bbe5228050007e11d8c6

#### Expected behaviour
cmd/rpcdaemon/commands/trace_filtering.go#L118

```
	traces, err := api.Transaction(ctx, txHash)       // same with api "trace_transaction"
	if err != nil {
		return nil, err
	}

	// 'trace_get' index starts at one (oddly)
	firstIndex := int(indicies[0]) + 1
	for i, trace := range traces {
		if i == firstIndex {
			return &trace, nil
		}
	}
	return nil, err
```
Why `firstIndex +1` here? When I was trying to get the first trace of a transaction i.e. `traces[0]`, should I use "-1" for the indicies parameter?
Are we trying to remove the first trace? But in api "trace_transaction", all traces were included in the result.

**Comment by tjayrush** [comment]
I am absolutely not speaking on behalf of the Erigon team, but I do have long experience with the `trace_` namespace having used it since the first Parity version of these APIs since around 2017.

The behaviour you describe has been in the code since the beginning. In `trace_transaction`, the first trace (i.e. trace[0]) is identical to the top-level transaction itself. So, for example, if you called `trace_transaction` on a straight EOA to EOA transfer of ETH, the trace would have all the same values for `from`, `to`, `value`, etc. The only difference is the `gasUsed` value which reflects the total gas used of the transaction as a whole minus `gasUsed` in the remaining traces. (In this example, that number would be zero, so the top-level transaction `gasUsed` and trace[0]'s `gasUsed` would be the same.)

I never quite understood why `trace_get` skipped the first trace`, but that may be why. Perhaps the semantics of `trace_get` are to get the nth actual smart contract trace and because the traces for the transaction start with a trace of the top-level transaction it skips over that.

Upshot: It's worked like this since the first release of the code, so I don't actually think this is a bug other than perhaps in the documentation.

**Comment by shu-unifra** [comment]
got it, thank you
