### ISSUE TITLE
debug_traceTransaction: handler crashed when tracer access to empty memory on LOG0 event

### ISSUE THREAD

**Issue by cattingcat** [ledgerwatch/erigon#5932]
According to docs, LOG* events has `offset` and `length` properties on stack, so I'm working on tracer that gets topics and other stuff from events, so I'm trying to get corresponding memory, but my tracer dies in some cases.

I investigated the issue, and it looks like the problem is with Erigon nodes.
When I do the same with geth - everything works fine, I got something like '0x' and so on, but erigon crashes the handler.

#### System information

Erigon version: `./erigon --version`
erigon/2.28.1

#### Expected behaviour
<img width="728" alt="image" src="https://user-images.githubusercontent.com/5341725/199280147-afd0b765-d41a-420d-a8f7-0f60f20290ec.png">

But with data field equal '0x' as geth returns

#### Actual behaviour
response with line: `method handler crashed`

#### Steps to reproduce the behaviour

`debug_traceTransaction` with this tracer
tx-hash with the problem: 0xaf9b8d324a5fdced183816f4cce2d5e0361f1a420925e8bf8039fc7f5a990f9a

```
{
  retVal: [],
  step: function(log,db) {
    var error = log.getError();
    if (error !== undefined) {
      this.fault(log, db);
      return;
    }
    var mnemonic = log.op.toString();

    if (mnemonic === 'LOG0') {
      var offset = log.stack.peek(0).valueOf();
      var len = log.stack.peek(1).valueOf();

      this.retVal.push({
        pc: log.getPC(),
        mnemonic: mnemonic,
        data: toHex(log.memory.slice(offset, offset + len)), // comment this line and everything works fine
        contract: toHex(log.contract.getAddress())
      });
    }
  },
  fault: function(log,db) {this.retVal.push("FAULT: " + JSON.stringify(log))},
  result: function(ctx,db) {return this.retVal},
}
```

**Comment by EnoRage** [comment]
+1

**Comment by maxUo** [comment]
+1

**Comment by a26nine** [comment]
Same here! The error: `RPC method debug_traceBlockByNumber crashed: interface conversion: interface {} is float64, not int64`.

**Comment by qk-santi** [comment]
Munching this as much as possible for the team, so we can get this solved asap.
**Bug and workaround below!**

Looking into a `LOG0` step from the transaction in the OP:
```
{
  pc: 85,
  op: 'LOG0',
  gas: 71955,
  gasCost: 375,
  depth: 1,
  stack: [
    '0x80',
    '0x61',
    '0x0',
    '0xa0e1182aab8c26713d1c3026463f44233b230bca'
  ],
  memory: [
    '0000000000000000000000000000000000000000000000000000000000000000',
    '0000000000000000000000000000000000000000000000000000000000000000',
    '00000000000000000000000000000000000000000000000000000000000000a0',
    '0000000000000000000000000000000000000000000000000000000000000000',
    '58327369a5c0db191697d11b0ac5637c3445d38af4b15b6000808080335af450'
  ]
}
```

By running these lines:
```
var offset = log.stack.peek(0).valueOf();
var len = log.stack.peek(1).valueOf();
```

We are setting:
```
offset = 0xa0e1182aab8c26713d1c3026463f44233b230bca (in decimal equivalent)
len = 0
```

then when trying to slice the `memory` array, is when we get the error:
```
data: toHex(log.memory.slice(offset, offset + len)),
```

Error in log:
```
RPC method debug_traceTransaction crashed: interface conversion: interface {} is float64, not int64
```

So, let's focus on what exactly is making that exception.

Removing `toHex` still does break:
```
data: log.memory.slice(offset, offset + len),
```

So, it seems the **slice** function is the one to blame.
Using small numbers works:
```
data: log.memory.slice(0, 0),
```
Output:
```
    {
      "pc": 85,
      "mnemonic": "LOG0",
      "data": [],
      "contract": "0x99a5a8297e05954510ec30077f889d07ebe07154"
    }
```

If we use big numbers it fails
```
data: log.memory.slice(1e50, 0),
```

BUT, if we go under JS's `Number.MAX_SAFE_INTEGER` it works!!

```
data: log.memory.slice(0, 0),
```
Output:
```
    {
      "pc": 85,
      "mnemonic": "LOG0",
      "data": "0x",
      "contract": "0x99a5a8297e05954510ec30077f889d07ebe07154"
    }
```
When the **int** is bigger than *MAX_SAFE_INTEGER* and the tracer converts variables from JS to Go, probably some it is unexpected and the additional bits makes it be interpreted as a **float64** instead of a **int64** as the function definition states:
[func (mw *memoryWrapper) slice(begin, end int64) []byte {](https://github.com/ledgerwatch/erigon/blob/9ffc457cbb736f549394ef0319e43a4d924e4836/eth/tracers/tracer.go#L99)

So, there's a possible workaround 😄

## Workaround

Limit all int numbers to max JS's *Number.MAX_SAFE_INTEGER*.
Check this alteration won't change the expected output of your tracer.

```
{
    retVal: [],
    step: function(log,db) {
      var error = log.getError();
      if (error !== undefined) {
        this.fault(log, db);
        return;
      }
      var mnemonic = log.op.toString();

      if (mnemonic === 'LOG0') {
        var offset = log.stack.peek(0).valueOf();
        var len = log.stack.peek(1).valueOf();

        // Limit all ints to max Number.MAX_SAFE_INTEGER
        if (offset > 9007199254740991) offset = 9007199254740991; // MAX_SAFE_INTEGER

        this.retVal.push({
          pc: log.getPC(),
          mnemonic: mnemonic,
          data: toHex(log.memory.slice(offset, offset + 0)), // comment this line and everything works fine
          contract: toHex(log.contract.getAddress())
        });
      }
    },
    fault: function(log,db) {this.retVal.push("FAULT: " + JSON.stringify(log))},
    result: function(ctx,db) {return this.retVal},
  }
```

Output:
```
[...]
    {
      "pc": 85,
      "mnemonic": "LOG0",
      "data": "0x",
      "contract": "0x99a5a8297e05954510ec30077f889d07ebe07154"
    }
[...]
```

**Comment by qk-santi** [comment]
Keeping this open

**Comment by qk-santi** [comment]
Keeping this open

**Comment by qk-santi** [comment]
Keeping this open

**Comment by qk-santi** [comment]
Keeping this open

**Comment by qk-santi** [comment]
Keeping this open
