### ISSUE TITLE
Stuck at checkpoint sync no peers

### ISSUE THREAD

**Issue by phoneix1221** [ledgerwatch/erigon#6143]
Trying to sync archive node in ethereum mainnet , been almost a day stuck at checkpoint sync retrieving bootstrap peers=0. I guess this is because of Internal CL added in v2.3.0 , is this normal that checkpoint sync takes this long? 
command=/usr/local/bin/erigon --datadir=/home/erigon/mainnet --private.api.addr=0.0.0.0:8090 --metrics --metrics.addr 0.0.0.0 --torrent.download.rate=512mb
![erigon](https://user-images.githubusercontent.com/44673414/204301235-8a7bdcd2-54f9-43a6-9afa-87e6da0b407d.png)

**Comment by 23722** [comment]
I experience the same phenomenon.

OS: Ubuntu 20.04
Erigon version: v.2.30.0 running Docker with the standard settings (except port forwarding)

**Expected behavior**
Lightclient finds peers and retrieves bootstrap.

**Actual Behavior**
Lightclient does not find peers and does not retrieve bootstrap
`erigon-downloader-1` finds peers, downloads snapshots, then halts at 100.00% 247.4GB/247.4GB.

Logs after restarting containers:

`make docker-compose
Docker build args:
    DOCKER_UID: 3473
    DOCKER_GID: 3473

Ensuring host OS user exists with specified UID/GID...
✔️ host OS user exists: erigon
✔️ xdg_data_home setup
total 0
drwxrwxrwx 6 erigon erigon  79 Nov 29 15:02 .
drwxrwxrwx 3 erigon erigon  19 Nov 29 15:02 ..
drwxrwxrwx 7 erigon erigon 120 Nov 29 15:25 erigon
drwxrwxrwx 6    472 root    77 Nov 30 10:52 erigon-grafana
drwxrwxrwx 9 erigon erigon 228 Nov 30 10:55 erigon-prometheus
drwxrwxrwx 2 erigon erigon   6 Nov 29 15:02 nano
docker compose up
[+] Running 7/0
 ⠿ Container erigon-erigon-1      Recreated                                                                                                        0.0s
 ⠿ Container erigon-prometheus-1  Created                                                                                                          0.0s
 ⠿ Container erigon-grafana-1     Created                                                                                                          0.0s
 ⠿ Container erigon-rpcdaemon-1   Recreated                                                                                                        0.0s
 ⠿ Container erigon-downloader-1  Recreated                                                                                                        0.0s
 ⠿ Container erigon-txpool-1      Recreated                                                                                                        0.0s
 ⠿ Container erigon-sentry-1      Recreated                                                                                                        0.0s
Attaching to erigon-downloader-1, erigon-erigon-1, erigon-grafana-1, erigon-prometheus-1, erigon-rpcdaemon-1, erigon-sentry-1, erigon-txpool-1
erigon-grafana-1     | logger=sqlstore t=2022-11-30T10:56:59.953466447Z level=warn msg="SQLite database file has broader permissions than it should" path=/var/lib/grafana/grafana.db mode=-rwxrwxrwx expected=-rw-r-----
erigon-erigon-1      | [WARN] [11-30|10:57:00.081] no log dir set, console logging only
erigon-erigon-1      | [INFO] [11-30|10:57:00.081] Starting metrics server                  addr=http://0.0.0.0:6060/debug/metrics/prometheus
erigon-erigon-1      | [INFO] [11-30|10:57:00.081] Starting pprof server                    cpu="go tool pprof -lines -http=: http://0.0.0.0:6061/debug/pprof/profile?seconds=20" heap="go tool pprof -lines -http=: http://0.0.0.0:6061/debug/pprof/heap"
erigon-erigon-1      | [WARN] [11-30|10:57:00.088] no log dir set, console logging only
erigon-erigon-1      | [INFO] [11-30|10:57:00.088] Build info                               git_branch=devel git_tag=v2021.10.03-2356-gae6d00747-dirty git_commit=ae6d00747e0d619ba9c1f6632a90299377ccab65
erigon-erigon-1      | [INFO] [11-30|10:57:00.088] Starting Erigon on Ethereum mainnet...
erigon-erigon-1      | [INFO] [11-30|10:57:00.089] Maximum peer count                       ETH=100 total=100
erigon-erigon-1      | [INFO] [11-30|10:57:00.090] starting HTTP APIs                       APIs=eth,erigon,engine
erigon-erigon-1      | [INFO] [11-30|10:57:00.091] Set global gas cap                       cap=50000000
erigon-erigon-1      | [INFO] [11-30|10:57:00.149] Opening Database                         label=chaindata path=/home/erigon/.local/share/erigon/chaindata
erigon-erigon-1      | [INFO] [11-30|10:57:00.156] Initialised chain configuration          config="{ChainID: 1, Homestead: 1150000, DAO: 1920000, DAO Support: true, Tangerine Whistle: 2463000, Spurious Dragon: 2675000, Byzantium: 4370000, Constantinople: 7280000, Petersburg: 7280000, Istanbul: 9069000, Muir Glacier: 9200000, Berlin: 12244000, London: 12965000, Arrow Glacier: 13773000, Gray Glacier: 15050000, Terminal Total Difficulty: 58750000000000000000000, Merge Netsplit: <nil>, Shanghai: <nil>, Cancun: <nil>, Engine: ethash}" genesis=0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3
erigon-erigon-1      | [INFO] [11-30|10:57:00.156] Effective                                prune_flags= snapshot_flags="--snapshots=true" history.v3=false
erigon-erigon-1      | [INFO] [11-30|10:57:00.157] Initialising Ethereum protocol           network=1
erigon-erigon-1      | [INFO] [11-30|10:57:00.157] Disk storage enabled for ethash DAGs     dir=/home/erigon/.local/share/erigon/ethash-dags count=2
erigon-erigon-1      | [INFO] [11-30|10:57:00.158] Starting private RPC server              on=0.0.0.0:9090
erigon-erigon-1      | [INFO] [11-30|10:57:00.158] new subscription to logs established
erigon-erigon-1      | [INFO] [11-30|10:57:00.181] [Sentinel] Sentinel started              enr=enr:-Ly4QGPrxvi3NqzpV_r7vBcpLgR2w8LA5Nb8Bh8lWaSlrgIgAvpX9SQ0HmB_mMPdDfNIja6JBiwBCO6P4l0ocOgh300Bh2F0dG5ldHOIAAAAAAAAAACEZXRoMpBKJsWLAgAAAP__________gmlkgnY0gmlwhH8AAAGJc2VjcDI1NmsxoQL1GdudyVSaHX7nXMvEPIRAViNWLRieaFeGn77rWTMpfIhzeW5jbmV0cwCDdGNwgg-hg3VkcIIPoA
erigon-erigon-1      | [INFO] [11-30|10:57:00.186] [Checkpoint Sync] Requesting beacon state uri=https://beaconstate.ethstaker.cc/eth/v2/debug/beacon/states/finalized
erigon-txpool-1      | [WARN] [11-30|10:57:00.513] no log dir set, console logging only
erigon-txpool-1      | [WARN] [11-30|10:57:00.513] no log dir set, console logging only
erigon-txpool-1      | [INFO] [11-30|10:57:00.514] TxPool started                           db=/home/erigon/.local/share/erigon/txpool
erigon-txpool-1      | [INFO] [11-30|10:57:00.521] Started gRPC server                      on=0.0.0.0:9094
erigon-rpcdaemon-1   | [WARN] [11-30|10:57:00.669] no log dir set, console logging only
erigon-rpcdaemon-1   | [WARN] [11-30|10:57:00.669] no log dir set, console logging only
erigon-rpcdaemon-1   | [INFO] [11-30|10:57:00.670] DB schemas compatible                    reader=6.0.0 database=6.0.0
erigon-rpcdaemon-1   | [INFO] [11-30|10:57:00.677] [Snapshots] Blocks Stat                  blocks=0k indices=0k alloc=15.0MB sys=36.9MB
erigon-rpcdaemon-1   | [INFO] [11-30|10:57:00.678] rpc filters: subscribing to Erigon events
erigon-rpcdaemon-1   | [INFO] [11-30|10:57:00.678] HTTP endpoint opened                     url=0.0.0.0:8545 ws=true ws.compression=false grpc=false
erigon-txpool-1      | [INFO] [11-30|10:57:00.679] New txs subscriber joined
erigon-erigon-1      | [INFO] [11-30|10:57:00.679] new subscription to newHeaders established
erigon-rpcdaemon-1   | [INFO] [11-30|10:57:00.681] [Snapshots] Blocks Stat                  blocks=0k indices=0k alloc=15.9MB sys=37.1MB
erigon-rpcdaemon-1   | [INFO] [11-30|10:57:00.681] interfaces compatible                    remote_db= client=6.0.0 server=6.0.0
erigon-rpcdaemon-1   | [INFO] [11-30|10:57:00.681] [Snapshots] Blocks Stat                  blocks=0k indices=0k alloc=16.0MB sys=37.1MB
erigon-rpcdaemon-1   | [INFO] [11-30|10:57:00.682] interfaces compatible                    remote_service=eth_backend client=3.1.0 server=3.1.0
erigon-rpcdaemon-1   | [INFO] [11-30|10:57:00.682] interfaces compatible                    remote_service=mining client=1.0.0 server=1.0.0
erigon-rpcdaemon-1   | [INFO] [11-30|10:57:00.682] interfaces compatible                    remote_service=tx_pool client=1.0.0 server=1.0.0
erigon-downloader-1  | [WARN] [11-30|10:57:00.688] no log dir set, console logging only
erigon-downloader-1  | [WARN] [11-30|10:57:00.688] no log dir set, console logging only
erigon-downloader-1  | [INFO] [11-30|10:57:00.688] Run snapshot downloader                  addr=0.0.0.0:9093 datadir=/home/erigon/.local/share/erigon download.rate=16MB upload.rate=4MB
erigon-sentry-1      | [WARN] [11-30|10:57:00.694] no log dir set, console logging only
erigon-sentry-1      | [WARN] [11-30|10:57:00.695] no log dir set, console logging only
erigon-sentry-1      | [INFO] [11-30|10:57:00.695] Starting Sentry gRPC server              on=0.0.0.0:9091
erigon-sentry-1      | [INFO] [11-30|10:57:00.695] Sentry gRPC received connection          via=tcp6 from=0.0.0.0:9091
erigon-downloader-1  | [INFO] [11-30|10:57:01.500] [torrent] Start                          my peerID=2d4754303030332da504a094a42e8af1d89b6df9
erigon-downloader-1  | [INFO] [11-30|10:57:01.500] Started gRPC server                      on=0.0.0.0:9093
erigon-erigon-1      | [INFO] [11-30|10:57:16.012] [Checkpoint Sync] Retrieving lightclient bootstrap from sentinel root=7c0c60dbf27ba12d15486101a97f997373a9c4c2d4bedf6a62b94fec8c19f78a
erigon-downloader-1  | [INFO] [11-30|10:57:21.501] [Snapshots] Downloading                  progress="0.00% 0B/0B" download=0B/s upload=0B/s peers=0 connections=0 files=0
erigon-erigon-1      | [INFO] [11-30|10:57:26.014] [Checkpoint Sync] Retrieving bootstrap   peers=0
erigon-erigon-1      | [INFO] [11-30|10:57:36.014] [Checkpoint Sync] Retrieving bootstrap   peers=0
erigon-downloader-1  | [INFO] [11-30|10:57:41.501] [Snapshots] Downloading                  progress="100.00% 247.4GB/247.4GB" download=0B/s upload=0B/s peers=0 connections=0 files=93
erigon-erigon-1      | [INFO] [11-30|10:57:46.013] [Checkpoint Sync] Retrieving bootstrap   peers=0
erigon-erigon-1      | [INFO] [11-30|10:57:56.014] [Checkpoint Sync] Retrieving bootstrap   peers=0`

Before restart, Checkpoint Sync already happened for 12h+

**Comment by idanya** [comment]
Same here. Ethereum mainnet sync does not start. The following Log just keeps repeating 
```
INFO[01-02|06:05:44.982] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[01-02|06:05:54.982] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[01-02|06:06:04.983] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[01-02|06:06:14.982] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[01-02|06:06:24.982] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[01-02|06:06:34.982] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[01-02|06:06:44.982] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[01-02|06:06:54.982] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[01-02|06:07:02.799] [p2p] GoodPeers                          eth66=0
INFO[01-02|06:07:04.983] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[01-02|06:07:14.982] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[01-02|06:07:24.982] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[01-02|06:07:34.982] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[01-02|06:07:44.982] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[01-02|06:07:54.982] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[01-02|06:08:04.984] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[01-02|06:08:14.982] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[01-02|06:08:24.982] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[01-02|06:08:34.983] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[01-02|06:08:44.989] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[01-02|06:08:54.982] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[01-02|06:09:02.799] [p2p] GoodPeers                          eth66=0
INFO[01-02|06:09:04.983] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[01-02|06:09:14.983] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[01-02|06:09:24.982] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[01-02|06:09:34.982] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[01-02|06:09:44.982] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[01-02|06:09:54.982] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[01-02|06:10:04.982] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[01-02|06:10:14.982] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[01-02|06:10:24.982] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[01-02|06:10:34.982] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[01-02|06:10:44.982] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[01-02|06:10:54.982] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[01-02|06:11:02.799] [p2p] GoodPeers                          eth66=0
INFO[01-02|06:11:04.982] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[01-02|06:11:14.982] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[01-02|06:11:24.982] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[01-02|06:11:34.982] [Checkpoint Sync] Retrieving bootstrap   peers=0
INFO[01-02|06:11:44.984] [Checkpoint Sync] Retrieving bootstrap   peers=0
```

**Comment by 23722** [comment]
I resolved the issue for myself. 

Short: The ports were not exposed to the Internet.

Long: My server is located in an eduroam network. eduroam is a DMZ, so ports might be open at the server but not exposed to the Internet due to the eduroam firewall. In my case, I resolved the issue by getting in contact with the eduroam admins. They opened the relevant ports for Erigon and Lighthouse (ports: `30303`, `9000`; protocols: TCP, TCP6). Make sure to let the admins open the ports for your external IP address: `wget -qO- ifconfig.me/ip`
