### ISSUE TITLE
eth_getBlockReceipts by Block Hash

### ISSUE THREAD

**Issue by MRabenda** [ledgerwatch/erigon#6229]
# Rationale

Why should this feature exist?
For each block transactions receipts can be different, it would be very useful to be able to get all receipts by given block hash

What are the use-cases?
All use cases which are taking block hash as identified instead of block number which is reorg resilient

# Implementation

Do you have ideas regarding the implementation of this feature?
...

Are you willing to implement this feature?
If required and approved by a team I can work on this eventually.

**Comment by AskAlexSharov** [comment]
Erigon doesn't store non-canonical receipts for now.

**Comment by MRabenda** [comment]
@AskAlexSharov - can you explain what means non-canonical?

**Comment by AskAlexSharov** [comment]
@enriavil1 @MRabenda 2 questions plz:
1. If we Erigon doesn't store non-canonical receipts, then get receipts by BlockNum is enough. Yes?
2. What purpose API which return ALL receipts of given block - Instead of filter useful logs by eth_getLogs? What is use-case? Just copy all Erigon's data to another DB for analytics or there is some other use-cases?

**Comment by MRabenda** [comment]
@AskAlexSharov copy to another DB for analytics not only Logs but a full receipt. But when you are building analytics with reorg proven and all EVM entities has to be synced - calling by blockHash is a much more accurate way than by blockNumber (which for Ethereum, Polygon etc at block hear to head can reorg often)

**Comment by AskAlexSharov** [comment]
Good feedback

**Comment by MRabenda** [comment]
I copied this from @enriavil1 code :D

**Comment by MRabenda** [comment]
Thanks @AskAlexSharov @enriavil1 !
