### ISSUE TITLE
Unstable issue, keep showing [2/16 Headers] No block headers to write in this log period block number=23422481

### ISSUE THREAD

**Issue by calmbeing** [ledgerwatch/erigon#6235]
#### System information
linux, 8TB, 64GM memory
Erigon version: `./erigon --version`
erigon version 2.30.0-dev-d5199f52
OS & Version: Windows/Linux/OSX
Linux
Commit hash : d5199f521bfabc9ed1fa0f8cc6a05d5253872be1
#### Actual behaviour
Running for bsc archive node, keep showing  [2/16 Headers] No block headers to write in this log period block number=23422481, and similar issue already raised by  #5703 but still open without conclusion yet.
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/99724749/206173457-d20a83d5-a7a7-4694-996a-8626197b284b.png">

#### Steps to reproduce the behaviour
` ./build/bin/erigon --chain bsc --datadir=/server/home/qa/eri/erigon/data`
I have tried to commented the usage of function `HeadersPOW` because it's obviously no POW usage in bsc, still not work.

**Comment by temuera** [comment]
> a lot of people with the same issue...
None of the versions for BSC can work correctly now :(((((((((((((((((((((((

**Comment by egorFiNE** [comment]
Yes, it happens on both Polygon and BSC every other day or daily.

Makes using Erigon impossible. We had to switch to bor (geth) for Polygon a couple of days ago and we will be forced to switch to geth on BSC as well

**Comment by dwjorgeb** [comment]
> Yes, it happens on both Polygon and BSC every other day or daily.
> 
> Makes using Erigon impossible. We had to switch to bor (geth) for Polygon a couple of days ago and we will be forced to switch to geth on BSC as well

will probably have to do it also. Would be awesome if the dev team would give us an idea of when this might be fixed

**Comment by dwjorgeb** [comment]
@AlexeyAkhunov

**Comment by PolarSyncZ** [comment]
@AskAlexSharov This issue is all over the place, if it's not fixed in the next release, prior to the BSC gibbs hardfork this will impact everyone running BSC on erigon. I am currently running on 2.28 and have been relatively stable but this will force an upgrade that will break all of the bsc systems if this issue isn't sorted out.

**Comment by AlexeyAkhunov** [comment]
Yes, I will be looking at it. This is the result of trying to accommodate the changes required for ETH main net "Merge", and it looks like a serious regression has been introduced. It would be useful to know what was the last version that worked well

**Comment by PolarSyncZ** [comment]
@AskAlexSharov I first noticed the issue in 2.27. I am running an ETH node on 10.1 and have not seen this problem occur.

**Comment by AlexeyAkhunov** [comment]
> @AskAlexSharov I first noticed the issue in 2.27. I am running an ETH node on 10.1 and have not seen this problem occur.

Thank you. I have a plan for now on how to deal with it, will try to do it asap

**Comment by AlexeyAkhunov** [comment]
Update
![telegram-cloud-photo-size-4-5814610189880507144-y](https://user-images.githubusercontent.com/13686139/206931524-06533a22-fe37-4b44-853a-f29641db8544.jpg)

**Comment by AlexeyAkhunov** [comment]
PR merged to `devel`: https://github.com/ledgerwatch/erigon/pull/6281

Hope it helps

**Comment by PolarSyncZ** [comment]
fwiw until there is an official confirmed patch...increasing the maxpeers seems to keep things more stable. I run with many more peers than most on some nodes to achieve the lowest latency when receiving blocks and have had far fewer failures on those nodes than the ones with less peers.

**Comment by dwjorgeb** [comment]
> fwiw until there is an official confirmed patch...increasing the maxpeers seems to keep things more stable. I run with many more peers than most on some nodes to achieve the lowest latency when receiving blocks and have had far fewer failures on those nodes than the ones with less peers. This makes sense if the issue is what is referenced above...more peers with the older version=less failures.

how many peers do you have?

**Comment by malise800** [comment]
I am currently running `Build info git_branch=devel git_tag=v2.31.0-rc.4-33-g4c02fef32 git_commit=4c02fef32340d439d16ad412cd15acddf85c266e` however it doesn't look like it fixed anything so far.

**Comment by alexlee85** [comment]
> 

same here, I'm running on 
`git_branch=devel git_tag=v2.31.0-rc.4-36-g5616ec252-dirty git_commit=5616ec25291756bd3615db3322a77a5d524a2e97`

**Comment by PolarSyncZ** [comment]
> > fwiw until there is an official confirmed patch...increasing the maxpeers seems to keep things more stable. I run with many more peers than most on some nodes to achieve the lowest latency when receiving blocks and have had far fewer failures on those nodes than the ones with less peers. This makes sense if the issue is what is referenced above...more peers with the older version=less failures.
> 
> how many peers do you have?

I'm running with 150 right now.

**Comment by calmbeing** [comment]
Worked well since pr #6281 merged, thanks @AlexeyAkhunov

**Comment by malise800** [comment]
bsc archival as well .. after finishing downloading the snapshot

**Comment by nikolinsko** [comment]
still happening for bsc on latest release v2.32.0

**Comment by egorFiNE** [comment]
Can confirm, happens almost daily on 2.32.0.

**Comment by bretep** [comment]
Happening to me as well. @AlexeyAkhunov you probably need to re-open this issue.

**Comment by bretep** [comment]
After about 30 minutes, inserting headers continued. I am keeping an eye on it. Maybe it has been resolved? Running `v2.32.0`

**Comment by bretep** [comment]
I tracked this down to DNS Discovery. It only happens on non-mainnet chains. See, no matter what you do, your client will be discovering eth mainnet nodes, and it causes a timeout to increase until it can try new nodes.

The workaround is to disable using `--nodiscover` and telling your server to use a bootnode(s) using `--bootnodes`

This does not work: `--discovery.dns=""` because this was copied from upstream `go-ethereum,` and erigon has added a discover layer that completely ignores that setting.

I had a fix for this but backed it out with a different solution for the chain I am working on. If I get some time this week, I'll re-implement it again and then send in a PR.

cc: @AlexeyAkhunov @AskAlexSharov

**Comment by AskAlexSharov** [comment]
@bretep wow

**Comment by bretep** [comment]
Did you add the `--bootnodes` and add a bootnode? If not, then it will just hang like before.

**Comment by bretep** [comment]
Regardless, if you are syncing another chain, you should never be mixing in the ethereum mainnet nodes into your discovery pool.

I can confirm, when I removed the ethereum mainnet, I was able to sync six nodes, with no problem.

**Comment by bretep** [comment]
Alright, after thinking about how to best resolve this issue, I think the solution I'm using is the correct resolution vs. the changes I originally backed out.

I will have a PR later today. I need to ensure this is the proper fix.

**Comment by bretep** [comment]
This is a much more complex answer than I’m willing to write out, especially on a phone. 

High level: erigon has broken out discovery into its own module. The internals of the p2p keep a table of peers to connect to, penalties, rate limits, etc… Nodes to connect to is based on an algorithm that tries to balance connections to different nodes. 

Both geth and erigon have the issue where they include ethereum mainnet when using dns discovery. Only erigon has the issue of disabling DNS discovery. 

To fully understand you will need to understand the p2p module in it’s entirety, which I had to to a year ago and a week ago (before I ran into this issue.) It’s fairly complex. 

This was not a simple bug to unravel, and in fact will likely improve syncing chains which are not mainnet for everyone. 

The fact that it seems more common now, may just be a red herring that more people are syncing bsc with erigon. I don’t see a reason this would not have been an issue since forever. 😉

I do know this resolves the issue.

**Comment by bretep** [comment]
The gist is, the reason you see this message over and over is you are stuck in the header syncing loop and it has a timer that prints out this message. Within that loop it’s waiting on a good peer to sync with.

**Comment by bretep** [comment]
Alright, the issue I described is real, but it only affects my chain because we have the exact genesis as ethereum mainnet. All the others should be fine. 🤦🏻‍♂️

Disabling DNS discovery is still an issue, but as long as you do not have the exact genesis, you won't get all the bad peers from DNS discovery. 

My bad.

**Comment by bretep** [comment]
@cifer76 So the next thing to figure out is where your client is stuck in: https://github.com/ledgerwatch/erigon/blob/devel/eth/stagedsync/stage_headers.go#L791
