### ISSUE TITLE
Increase thread & db read throughput?

### ISSUE THREAD

**Issue by plvnts** [ledgerwatch/erigon#6443]
Follow up to https://github.com/ledgerwatch/erigon/issues/2245
We are looking to increase throughput on a node. Currently, the max number of threads created by Erigon equals the number of CPU cores. We would like to increase the number of threads as well as max. DB connections, which seem to be another hard limit.

Launching Erigon with flags --rpc.batch.concurrency=1000 --db.read.concurrency=1000 doesn't affect speed in any way which seems strange, considering that the defaults are much lower. What is the recommended way to increase # of threads and read concurrency? Thanks

**Comment by J-A-M-E-5** [comment]
I doubt there's a recommended way other than faster storage (maybe some efficient but higher-data-loss-risk RAID0 arrays with a dedicated controller?), faster CPU, more memory. I've done all these things albeit on old hardware, e.g. SATA SSD instead of NVMe.

Presuming your goal is simply faster performance one thing I did for a noticeable performance boost was to turn off CPU mitigations.

Don't do this if your server is used by anybody untrusting, if you run other services connected to internet, or if you run any virtual machines on it used by others, as it opens a wide and well documented security holes on your machine. But as a last resort if you can control access to your machine and do sensible things such as firewall the heck out of it, it does provide a very notable performance boost (I saw around 15% quicker for the entire sync).

https://leochavez.org/index.php/2020/11/16/disabling-intel-and-amd-cpu-vulnerability-mitigations/

**Comment by AskAlexSharov** [comment]
1. What doing your test? What RPC calls? Do you need serve much historical data or mostly recent data? In simple requests or in batch requests? What is more important - latency of 1 batch request or throughput of parallel users requests? Is it erigon’s built-in rpcdaemon or dedicated (with —datadir or without?)?
2. About disk and ram - look at OS PageCache hard-misses / sec - if your test does increase it a then increasing RAM amount or Disk read latency or —db.read.concurrency may help. If not increasing - then all your hot data fit in RAM and scale CPU make more sense, or reduce —db.read.concurrency. 
3. To optimize Erigon you can show us next 2 pics:
```
add —pprof flag 

go tool pprof -alloc_objects -png  'http://127.0.0.1:6060/debug/pprof/heap' > mem.png

go tool pprof -png 'http://0.0.0.0:6001/debug/pprof/profile?seconds=20' > cpu.png
```
