### ISSUE TITLE
i change dirpath everything renew

### ISSUE THREAD

**Issue by SuperEdison** [ledgerwatch/erigon#6756]
i cp old erigon dirpath to new path and then start erigon, index need calculate
![image](https://user-images.githubusercontent.com/84554944/215928802-58d22638-5aa4-4a0e-8a99-bfc55118ccff.png)

**Comment by AskAlexSharov** [comment]
it's protection from modification of snapshots after index build, also by-design nodes in network must have different indices (with different crypto-seed) to protect against unbalance-index attack.
But, if you know that backup was valid, it's ok to do something like:
`touch -d "2024-01-01T00:00:00" <datadir>/snapshots/*.idx`

it's not very user-friendly and likely we will change it in the future, but not very soon due to priorities.
