### ISSUE TITLE
Replay chain history from just the torrent snapshot data

### ISSUE THREAD

**Issue by sslivkoff** [ledgerwatch/erigon#6933]
Hi

I'm trying to rebuild ropsten state history. The ropsten torrent snapshots are still seeded and I was able to download them, but there are no peers left in the network to perform an actual sync

Is there a way to have Erigon to use only these snapshot files to rebuild the chain without any CL / peers?

Thanks

**Comment by J-A-M-E-5** [comment]
I suspect your problem is lack of synced CL, as it should after going backwards from latest slot sync up to whatever you have in state history (snapshots).

I've added ropsten support back into my erigon so you might wanna do that and run a later version. I've not synced that much past block 13,096,606 which is the last one on etherscan.

Not sure about internal consensus engine and I wouldn't bother trying to use it and go with an external CL. I keep my Nimbus running, and Nimbus right now has ~35 peers for Ropsten. Do you have .era files?  With 16GiB of era files you should be able to get a full archival Nimbus node running Ropsten very quickly at head.

Nimbus has removed Ropsten support, but it's easy to put back in by just specifying a config folder instead of "ropsten" for the network parameter. See this ticket:-  https://github.com/status-im/nimbus-eth2/issues/4593
