### ISSUE TITLE
Optimize some RPC requests internally

### ISSUE THREAD

**Issue by ozgrakkurt** [ledgerwatch/erigon#6936]
Hey!

It seems like a batch of getBlockByNumber or a batch of getTransactionReceipt requests are handled in different goroutines. And this seems like it would be a big performance bottleneck.

Would it make sense to just recognize when the request is a batch of consecutive getBlockByNumber requests and convert it into a single internal request and handle it that way?

I am willing to implement this with some guidance

**Comment by AskAlexSharov** [comment]
@ozgrakkurt 
1. fyi we have --rpc.batch.concurrency, --rpc.batch.limit
2. such solution may be good, but has much corner-cases:
- what if all this requests are for old historical blocks (which are not in PageCache)? In this case you may want to parallelize them just because all of them will be disk-io-bounded (also it depends on disk type)
- what if some software like TheGraph want to fetch all historical blocks? (They likely can control parallelism on their end by controlling amount/size of batches). 
- do you think it will give us good performance profit for hot-recent blocks which are in baseApi.blocksLRU? I mean - maybe bottleneck is not in goroutines, but in json marshal/unmarshal. 
3. what is your use-case?
4. we have streaming support - in theory can send response to client when it's ready. But some users asked us to preserve order of request/response in batch (event that there is requrestID). Make something non-concurrent way will give use obvious order preserving and we can stream responses in this case.

**Comment by ozgrakkurt** [comment]
1. I tried those but couldn't get it to be significantly faster
2-3. My use case is the same as TheGraph. I am getting all data sequentially using batched getBlockByNumber reqs and getLogs reqs. I was guessing this data is fairly sequential in kv-store so opening an iterator and going through it would be more efficient than making parallel get requests.
4. I'm using HTTP and the code needs to be compatible with many rpc providers so I don't think streaming support would work for me.

**Comment by AskAlexSharov** [comment]
- “ fairly sequential in kv-store so opening an iterator and going through it would be more efficient than making parallel get requests” - you are right - yes, we moving from O(log n) to O(1). but true is Data >> Ram and disk touches may eat the difference anyway and json may eat the difference. Also FYI complexity of Get from frozendb (snapshots folder) is O(1) (but need touch semi-random place of .idx file). So, it can be a good idea, but need bench, my head can’t estimate.
- streaming is optional 
- FYI: Some disks like gp3 are tuned for high parallel throughput and high latency
