### ISSUE TITLE
Limit capacities of maps in sendersBatch

### ISSUE THREAD

**Issue by Qjawko** [ledgerwatch/erigon#7002]
# Rationale

The `sendersBatch` structure is currently using too much CPU and memory, as well as allocating a large amount of resources. As a result, when the flush function starts iterating over a map, it takes a significant amount of CPU time due to [Go's standard map's evacuation mechanism](https://go.dev/src/runtime/map.go#L926). In order to improve the efficiency of Erigon's staged sync and other components, it would be helpful to optimize or limit the use of maps.

[CPU profile ](https://user-images.githubusercontent.com/28804621/222441686-a6acdfa1-6432-490a-be63-32bd337fd526.png)
[Memory profile](https://user-images.githubusercontent.com/28804621/222441852-6c0ff2ff-ce7b-47f3-a13f-33c6ecf77fa5.png)

# Implementation

Add flags `txpool.senders.cache_capacity` and `txpool.flush_every` or even another data structure instead of std map. 
Let's discuss our ideas how to do it and I am willing to implement this feature.

**Comment by AskAlexSharov** [comment]
As I remember `p.senders` was added to enumerate all senders - give them uint64 ID instead of using their addr (in all other data structures).

In flush I see:
```
for addr, id := range p.senders.senderIDs { // no inverted index - tradeoff flush speed for memory usage
	if id == metaTx.Tx.SenderID {
		copy(v[:20], addr)
		break
	}
}		
```
But seems it's not true and we have inverted index already: p.senders.senderID2Addr 
Just need use it instead of brude-force

I don't really remember now: `p.senders` is the cache (which can be limited) or enumeration (primary index) which can't. In my head it can't be limited, but it must not keep any trash: id's of senders which not used in any other in-mem data structures. (maybe I'm wrong). 

In-theory can persist `p.senders` in TxPool's DB: but I don't have intuition - is it good idea or not. 

`p.senders` has 2 fields: senderIDs and senderID2Addr which now seems store add twice. They must share memory: `senderIDs` string must keep the addr and `senderID2Addr` must refer to that memory (In Golang when cast string to []bytes - it doesn't copy).

About `txpool.flush_every` - yes need add such CLI option

**Comment by Qjawko** [comment]
> In Golang when cast string to []bytes - it doesn't copy
I don't think so because strings in Go are immutable, and without a copy it would be possible to modify the contents of the string (by changing the elements of the byte slice), WDYT? Maybe we should try to use non-copy **unsafe** operation in getOrCreateID method ([]byte -> string) to reduce memory allocations, at the moment I don't see mutable operations on the address byte slice.

**Comment by AskAlexSharov** [comment]
@Qjawko you are right. anyway that zero-copy thing is just 2x saving. likely we need 10x or hard-limit.

**Comment by Qjawko** [comment]
I'll try to fix and add features we discussed above and profile again. Will post it here or in PR

**Comment by AskAlexSharov** [comment]
`addrB` is already `[20]byte` - just need add method `getOrCreateID(` for this type

**Comment by Qjawko** [comment]
Sorry, I mean change it in senderBatch structure and methods, here is an example

```
type sendersBatch struct {
	senderIDs     map[[20]byte]uint64
	senderID2Addr map[uint64][20]byte
	tracedSenders map[[20]byte]struct{}
	senderID      uint64
}
```

**Comment by AskAlexSharov** [comment]
yes, `senderID2Addr` to `map[uint64]common.Address`
I don't have intuition about `map[string] vs map[[20]byte]` perf. Maybe it also will reduce RAM pressure.

**Comment by AskAlexSharov** [comment]
I think: it's not common.Address only because minedTxs.Senders.At(i) return this type. 
As I remember - now in Go can cast []byte to *[20]byte without allocation. 

FYI: We keep compatibility with go 1.18 now. But can move to 1.19 if some super-useful feature is needed here.

**Comment by Qjawko** [comment]
Maybe we should change it to common.Address too?

**Comment by AskAlexSharov** [comment]
@Qjawko see https://go.dev/doc/go1.17#

"change it to common.Address" i don't know will it make things better or worse. now `minedTxs.Senders` it's single []byte
