### ISSUE TITLE
how to execute blocks faster as soon as possible

### ISSUE THREAD

**Issue by SuperEdison** [ledgerwatch/erigon#7048]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. For general questions please use [Erigon's discord](https://discord.gg/hQ2dxbNZ).
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/84554944/223439529-01222a7d-2482-43a1-b150-ce079aae62da.png">
how to execute blocks faster as soon as possible by some param?   the node have had achieve data, and I had deleted chaindata dir file, snapshot dir had downloaded.

**Comment by J-A-M-E-5** [comment]
Memory, CPU (max GHz is important, not core count. Ensure CPU running in max performance mode and not power saving), Storage - NVMe SSD is better than SATA3 SSD. If you only have SATA SSD then two in a RAID0 array is faster. More advanced (and dangerous) stuff like turning off CPU Mitigations, or changing caching parameters of drive which is only sensible if you have UPS.

Having snapshots will only speed up downloading (as it doesn't need to download them) which is just a small part of the sync process.

**Comment by AskAlexSharov** [comment]
Usual bottlenecks are:
- raid miss-configuration (try tune for random read latency, not throughput)
- small ram 
- FileSystem does add significant overhead: like BtrFs-AutoDefrag or ZFS-compression. Can fix by switch to Ext4
- blocks are not equal: ddos attacks to netwrok, etc...
- can try `integration warmup --bucket=PlainState
- bigger --batchSize will help when: slow disk and big ram

I will close this issue - because it has no detailed information about machine, etc... No info about disk/filesystem/os/go version/cc version/erigon version/raid/ram/...
