### ISSUE TITLE
How to using Prysm with erigon?

### ISSUE THREAD

**Issue by TangMonk** [ledgerwatch/erigon#7093]

**Comment by thorstenhirsch** [comment]
You need to make sure that prysm can "talk" to erigon via the `authrpc` connection, which means:

- you generate a shared secret for both of them, a file called `jwt.hex` and copy it to each client's datadir
- erigon should open port 8551 for communication, but you might need to add `--authrpc.addr=0.0.0.0` and `--authrpc.vhosts=*` so that prysm can reach it
- and for prysm you add `--execution-endpoint=http://localhost:8551`

More options are available for custom ports and custom paths or names of `jwt.hex` and of course you can find more about it in the documentation, e.g.: https://docs.prylabs.network/docs/execution-node/authentication

**Comment by TangMonk** [comment]
> You need to make sure that prysm can "talk" to erigon via the `authrpc` connection, which means:
> 
> * you generate a shared secret for both of them, a file called `jwt.hex` and copy it to each client's datadir
> * erigon should open port 8551 for communication, but you might need to add `--authrpc.addr=0.0.0.0` and `--authrpc.vhosts=*` so that prysm can reach it
> * and for prysm you add `--execution-endpoint=http://localhost:8551`
> 
> More options are available for custom ports and custom paths or names of `jwt.hex` and of course you can find more about it in the documentation, e.g.: https://docs.prylabs.network/docs/execution-node/authentication

Thanks, Could geth and erigon share same prysm instace at one machine?
