### ISSUE TITLE
Chaindata Compression

### ISSUE THREAD

**Issue by thorstenhirsch** [ledgerwatch/erigon#7106]
# Rationale
Why should this feature exist?
- Polygon mainnet chaindata is at ~5.9 TB, which can be compressed even with performance-focused algorithms like lz4 to ~2.2 TB (on file level with MDBX backend, so I'm speaking of mdbx.dat)
- Huge storage requirements drive up the costs to operate nodes in the cloud

What are the use-cases?
- All blockchains with huge chaindata

# Implementation
Do you have ideas regarding the implementation of this feature?
- Compression on dataset (value) level probably won't cut it, my gut feeling is we need to compress the whole database
- Some guys use filesystem compression, which is available in btrfs and zfs, but AFAIK they don't compress on file level, but only records, which are very small parts, thus reaching muss less compression (~10%)
- From a user perspective it's favourable to get compression from the application, i.e. erigon or ergion's kv db backend instead of instructions for using specific filesystems with special configurations, especially when its data can be compressed as good as the chaindata

So let's discuss alternatives in this issue...

# MDBX
- According to my research it is not possible to implement lz4 compression in mdbx at file/memory level due to mmap
- A recent research paper [1] even dismisses the suitability of mmap for transactional databases completely
- Erigon's abstraction layer for the KV database backend should make it easy to switch away from MDBX, or at lease provide a configurable alternative

Are you willing to implement this feature?
- Yes, but I know that one does not simply write a resilient, transactional, performant DB backend. Let's first checkout if there are other backends available, which might have performed worse compared to MDBX so far, but which are suitable for lz4 compression.
- What do you think about persy [2], sled [3], or btree [4]?

[1] - https://cs.brown.edu/people/acrotty/pubs/p13-crotty.pdf
[2] - https://persy.rs
[3] - https://github.com/spacejam/sled
[4] - https://github.com/notjustinshaw/btree

**Comment by AskAlexSharov** [comment]
In general:
- compression - means you need RAM for 2 things: compressed and uncompressed data. mans you will have more RAM pressure/CPU caches eviction/loose zero-copy nature of db, etc...
- "suitability of mmap for transactional databases completely" - too big topic, too depends on workload, too depends on features required, too depends on implementation of "non-mmap database in vacuum", too depends on disk type, ...
- "Erigon's abstraction layer for the KV database backend" - we already have abstraction layer - but it using so much db features that you can't imagine. 
- "Some guys use filesystem compression" you may gain 2x on size here.

What is done: 
- Erigon2 moved historical blocks and TxLookup (by tx hash) index from chaindata to `datadir/snapshots`. They are compressed (by file-based compression, not block-base), immutable, way more compact indices (because of immutable property), data stored sequential in this files means more predictable read pattern (means can use madvise), etc...
- Erigon3 moving state history (and related indices) from chaindata to `datadir/snapshots/history`. Not all this snapshots are compressed now - but maybe we will turn-on more compression here in future. Erigon3 is not released yet, but getting close. 
- Erigon4 plan to move cold parts of current state from chaindata to `datadir/snapshots/history`.

**Comment by thorstenhirsch** [comment]
Thank you very much @AskAlexSharov. So I guess I should wait for the release of Erigon3 before doing something stupid. ;-) 
Just let me know if there's a small task I can help with.

**Comment by AskAlexSharov** [comment]
@thorstenhirsch if you interesting - you can work on compression-related things. To optimize: 
- compressor or decompressor: in “erigon-lib/compress”
- speed of build/read index: in “erigon-lib/eliasfano32”
