### ISSUE TITLE
Erigon gets killed because system is out of memory

### ISSUE THREAD

**Issue by SuchJitter** [ledgerwatch/erigon#7426]
#### System information

Erigon version: `2.43.0-stable-7e8beecf`

OS & Version: `CentOS 8`

Erigon Command (with flags/config):
`./erigon --chain=mainnet --datadir=/home/neweth --authrpc.jwtsecret=/opt/jwtsecret  --private.api.addr=0.0.0.0:9090  --http.addr=0.0.0.0 --ws --ws.compression=true --db.read.concurrency 100 --rpc.batch.concurrency 100 --rpc.batch.limit 100000  --http.api=eth,erigon,web3,net,debug,trace,txpool`

Concensus Layer: `Prysm`

Concensus Layer Command (with flags/config):
`./prysm.sh beacon-chain --execution-endpoint=http://localhost:8551 --accept-terms-of-use=true --jwt-secret=/opt/jwtsecret --datadir=/home/eth2/eth2`

Chain/Network: `Mainnet`

#### Expected behaviour
Regular syncing and handling RPC requests

#### Actual behaviour

tripping over eth_unsubscribe function and eventually getting killed by the OS.

Launching and killing happens within 30 minutes, looks like it depends on the amount of RPC calls that happen, might have to do something with memory leaks? The machine has 64GB of ram

[eth_unsubscribe errors](https://gyazo.com/45320b4e2bd1805602e07a6a94d83216)

`[16499191.786140] Out of memory: Killed process 3392009 (erigon) total-vm:23337403712kB, anon-rss:55008180kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:2540008kB oom_score_adj:0`

#### Steps to reproduce the behaviour
Regular syncing and having a couple of websockets connected to the node for RPC requests

#### Backtrace
None

**Comment by luncht1me** [comment]
I'm getting OOM kills on devel branch also, 16gb of physical RAM, 9gb Swap and swappiness value set to 10.

**Comment by AskAlexSharov** [comment]
I guess you are running in Docker, we don't support cgroupsv2 ram limit detection:  https://github.com/ledgerwatch/erigon/issues/6646#issuecomment-1425157327

you can reduce RAM usage by:
- a bit reduce GOMAXPROCS
- try add GOGC=50
- to understand where wasted RAM can do:
add flag --pprof
go tool pprof -inuse_space -png http://127.0.0.1:6060/debug/pprof/heap > mem.png
show this file
- reduce a bit --batchSize
- reduce a bit --bodies.cache
-

**Comment by luncht1me** [comment]
> don't believe 16GB is enough,

I'm at 7/15 on block 14mil, I've only ran into OOM once or twice, and seems to happen when my swap is full. I had an error when I tired reducing the `batchSize` to 128M so just chillin at 256M default. It seems to work quite well until eventually an exceptionally large block hits while RAM is tapped out.


> running in Docker,

I'm running bare metal, Manjaro. Not running inside a docker instance. Go version is 1.20. I only have a dual core + thread so don't really want to reduce `GOMAXPROCS` from 4 to 3 since it's already a fairly limited CPU as is.

I can try GOGC, that could be the problem, just GC being slightly larger than available RAM + Swap at certain large blocks. I had an IO error reducing batchSize but it may have just been a one-off and will try again.
