### ISSUE TITLE
The size of the db archive node of Polygon mainnet

### ISSUE THREAD

**Issue by 1scrooge** [ledgerwatch/erigon#8256]
Hello. I've to run Polygon archive node via Erigon client,  does anyone know the size of it database?

**Comment by mikolajsobolewski** [comment]
Our database with prune*.older 15768000  is 5.1Tb now

**Comment by psmahlii** [comment]
"prune*.older 15768000" its startup flag?

**Comment by mikolajsobolewski** [comment]
> "prune*.older 15768000" its startup flag?
yes, sure.

**Comment by gaia** [comment]
why 15768000? do i need to update this value from time to time? I don't want to run archive, only a validator node.

**Comment by mikolajsobolewski** [comment]
No we only need an archive for last year/

**Comment by 0xKrishna** [comment]
This is not an issue, Please use discord for queries.

**Comment by directsyndikat** [comment]
I have been trying to prune an archive node with the following command:
./build/bin/erigon --chain=bor-mainnet --bor.heimdall=https://heimdall-api.polygon.technology/ --datadir=/root/node/erigon --prune.h.older 5900000 --prune.r.older 5900000 --prune.t.older 5900000 --prune.c.older 5900000  --torrent.download.rate=512mb --state.cache=2GB --db.read.concurrency=1024 --rpc.batch.concurrency=18

Is this correct? since the last few times it attempted to start syncing from genesis
